<?php
declare(strict_types=1);
namespace Webbit\Manager;
require_once __DIR__.'/Session.php';
final class Members {
 private static function esc(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
 private static function input(string $key):string{return is_string($_POST[$key]??null)?$_POST[$key]:'';}
 public static function accountPath(string $private,string $name):string {if(!preg_match('/^[A-Za-z0-9_.-]{3,64}$/D',$name))throw new \RuntimeException('Invalid account');return $private.'/accounts/'.hash('sha256',strtolower($name));}
 private static function start(string $private,string $public):array {
  if(realpath($_SERVER['DOCUMENT_ROOT']??'')!==realpath($public)||realpath($public)===false)throw new \RuntimeException('Use public/ as document root.');
  AuthStore::privateDirectory($private,$public);Session::start($private,$public,true);
  $config=json_decode(file_get_contents($private.'/config.json'),true,32,JSON_THROW_ON_ERROR);return $config;
 }
 private static function auth(string $private,string $public,string $name):?AuthStore{$dir=self::accountPath($private,$name);if(!is_dir($dir)||is_link($dir)||is_file($dir.'/disabled')||!is_file($dir.'/auth.sqlite'))return null;return new AuthStore($dir,$public);}
 private static function rate(string $private):void{
  $file=$private.'/rate.sqlite';if(is_link($file))throw new \RuntimeException('Invalid storage');$db=new \PDO('sqlite:'.$file,null,null,[\PDO::ATTR_ERRMODE=>\PDO::ERRMODE_EXCEPTION]);chmod($file,0600);$db->exec('PRAGMA busy_timeout=5000');$db->exec('CREATE TABLE IF NOT EXISTS attempts(bucket TEXT PRIMARY KEY, n INTEGER, expires INTEGER)');$now=time();$bucket=hash('sha256',$_SERVER['REMOTE_ADDR']??'unknown');$db->exec('BEGIN IMMEDIATE');
  try{$clean=$db->prepare('DELETE FROM attempts WHERE expires < ?');$clean->execute([$now]);$q=$db->prepare('SELECT n FROM attempts WHERE bucket=?');$q->execute([$bucket]);$n=(int)$q->fetchColumn();if($n>=20)throw new \RuntimeException('Too many attempts. Wait 15 minutes.');$q=$db->prepare('INSERT INTO attempts VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET n=n+1');$q->execute([$bucket,$now+900]);$db->exec('COMMIT');}catch(\Throwable $e){$db->exec('ROLLBACK');throw $e;}
 }
 private static function loggedIn(string $private,string $public):bool {if(!is_string($_SESSION['member']??null))return false;$auth=self::auth($private,$public,$_SESSION['member']);return $auth!==null&&Session::authenticated(time(),$auth->epoch());}
 public static function page(string $private,string $public,string $id):void{try{$config=self::start($private,$public);if(!isset($config['pages'][$id]))throw new \RuntimeException('Unknown page');if(!self::loggedIn($private,$public)){header('Location: /members/');exit;}$path=$private.'/pages/'.$id.'.html';if(is_link($path)||!is_file($path))throw new \RuntimeException('Missing page');header("Content-Security-Policy: default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:; media-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'self'");header('Content-Type: text/html; charset=utf-8');readfile($path);}catch(\Throwable){http_response_code(503);echo 'Member content is unavailable. Check server setup.';}}
 public static function run(string $private,string $public):void{ini_set('display_errors','0');try{self::dispatch($private,$public);}catch(\Throwable){http_response_code(503);echo 'Member access is unavailable. Check HTTPS, private storage and server setup.';}}
 private static function dispatch(string $private,string $public):void{
  $config=self::start($private,$public);if((int)($_SERVER['CONTENT_LENGTH']??0)>8192){http_response_code(413);return;}$message='';$codes=[];
  if(($_SERVER['REQUEST_METHOD']??'')==='POST'){try{Session::requireCsrf(self::input('csrf'));$action=self::input('action');
   if($action==='logout'){Session::logout();header('Location: /members/');return;}
   self::rate($private);
   if($action==='login'){$name=strtolower(self::input('username'));$auth=self::auth($private,$public,$name);if(!$auth||!$auth->authenticate($name,self::input('password'),self::input('factor'),$_SERVER['REMOTE_ADDR']??'',time()))throw new \RuntimeException('Sign-in failed. Check your credentials or try later.');Session::login(time(),$auth->epoch());$_SESSION['member']=$name;}
   elseif($action==='invite'){$name=strtolower(self::input('username'));$dir=self::accountPath($private,$name);$file=$private.'/invites/'.hash('sha256',$name).'.json';$invite=is_file($file)&&!is_link($file)?json_decode(file_get_contents($file),true):[];$token=self::input('token');if(strlen($token)!==64||($invite['expires']??0)<time()||!hash_equals($invite['hash']??'',hash('sha256',$token)))throw new \RuntimeException('Invalid or expired invitation.');if(is_link($dir))throw new \RuntimeException('Invalid storage');if(!is_dir($dir)&&!mkdir($dir,0700,true))throw new \RuntimeException('Cannot prepare account');$auth=new AuthStore($dir,$public);if($auth->initialized())throw new \RuntimeException('Account already enrolled.');$_SESSION['enroll']=['name'=>$name,'hash'=>$invite['hash'],'until'=>time()+600,'secret'=>$auth->encryptEnrollment(Totp::secret())];}
   elseif($action==='enroll'){$enroll=$_SESSION['enroll']??[];if(($enroll['until']??0)<time())throw new \RuntimeException('Start enrollment again.');$file=$private.'/invites/'.hash('sha256',$enroll['name']).'.json';$invite=is_file($file)?json_decode(file_get_contents($file),true):[];if(($invite['expires']??0)<time()||!hash_equals($invite['hash']??'',$enroll['hash']))throw new \RuntimeException('Invitation expired.');$auth=new AuthStore(self::accountPath($private,$enroll['name']),$public);$codes=$auth->initialize($enroll['name'],self::input('password'),$auth->decryptEnrollment($enroll['secret']),self::input('factor'),time());unlink($file);unset($_SESSION['enroll']);$message='Account created. Save these one-use recovery codes. Sign in using the next authenticator code.';}
  }catch(\Throwable $e){$message=$e instanceof \InvalidArgumentException?$e->getMessage():'Request failed. Check your credentials, invitation and authenticator code, or try again later.';}}
  $csrf='<input type="hidden" name="csrf" value="'.self::esc($_SESSION['csrf']??'').'">';echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Member access</title><link rel="stylesheet" href="/members/style.css"></head><body><main><h1>'.self::esc($config['title']??'Member access').'</h1><p>'.self::esc($message).'</p>';
  if($codes)echo '<pre>'.self::esc(implode("\n",$codes)).'</pre>';
  if(self::loggedIn($private,$public)){echo '<h2>Your pages</h2><ul>';foreach($config['pages'] as $page)echo '<li><a href="'.self::esc($page['url']).'">'.self::esc($page['label']).'</a></li>';echo '</ul><form method="post">'.$csrf.'<button name="action" value="logout">Sign out</button></form>';}
  elseif(isset($_SESSION['enroll'])&&($_SESSION['enroll']['until']??0)>=time()){$enroll=$_SESSION['enroll'];$auth=new AuthStore(self::accountPath($private,$enroll['name']),$public);echo '<p>Add this setup key to your authenticator, then confirm the current code.</p><code>'.self::esc($auth->decryptEnrollment($enroll['secret'])).'</code><form method="post">'.$csrf.'<label>New password (12–72 bytes)<input name="password" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><label>Authenticator code<input name="factor" inputmode="numeric" autocomplete="one-time-code" required></label><button name="action" value="enroll">Create member account</button></form>';}
  else echo '<form method="post">'.$csrf.'<label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><label>Authenticator or recovery code<input name="factor" autocomplete="one-time-code" required></label><button name="action" value="login">Sign in</button></form><details><summary>Have an invitation?</summary><form method="post">'.$csrf.'<label>Username<input name="username" autocomplete="username" required></label><label>Invitation token<input name="token" autocomplete="off" required></label><button name="action" value="invite">Set up account</button></form></details>';
  echo '<p><a href="/">Return to site</a></p></main></body></html>';
 }
}
