import React,{useState} from 'react';
import {blocks,blockFields,blockTypes,blockMarkup,insertMarkup,duplicateBlock,renameBlock,sourceNodes} from './blocks';
import {replaceElementText} from './preview';
import {removeElement,moveElement,setElementAttribute} from './inspector';
import {effects,applyEffects,effectValues,withEnhancements} from './effects';
import type {SiteProject} from './project';
export function BlockEditor({project,page,selected,onSelect,onChange,onError}:{project:SiteProject;page:string;selected:number|null;onSelect:(id:number)=>void;onChange:(files:Record<string,string>)=>void;onError:(message:string)=>void}){
 const [catalog,setCatalog]=useState(false),[kind,setKind]=useState('text'),[title,setTitle]=useState('Your heading'),[items,setItems]=useState('First item\nSecond item\nThird item');
 const source=project.files[page]??'',outline=blocks(source),active=outline.find(b=>b.id===selected);
 const perform=(fn:()=>Record<string,string>)=>{try{onChange(fn());}catch(e){onError(String(e));}};
 const edit=(fn:()=>string)=>perform(()=>({...project.files,[page]:fn()}));
 return <section className="block-editor"><div className="side-heading">PAGE BLOCKS</div><button onClick={()=>setCatalog(!catalog)}>+ Add block / section</button>{catalog&&<div className="block-form"><label>Block type<select value={kind} onChange={e=>setKind(e.target.value)}>{blockTypes.map(([id,group,label])=><option key={id} value={id}>{group} · {label}</option>)}</select></label><label>Heading<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Items / paragraphs (one per line)<textarea value={items} onChange={e=>setItems(e.target.value)} rows={4}/></label><button onClick={()=>perform(()=>{let files={...project.files,[page]:insertMarkup(source,blockMarkup(kind,title,items))};if(['accordion','tabs','slider','filter'].includes(kind))files=withEnhancements(files,page);setCatalog(false);return files;})}>Insert at end of page</button>{active&&<button onClick={()=>perform(()=>{let files={...project.files,[page]:insertMarkup(source,blockMarkup(kind,title,items),active.id)};if(['accordion','tabs','slider','filter'].includes(kind))files=withEnhancements(files,page);setCatalog(false);return files;})}>Insert inside selected block</button>}</div>}
 <div className="block-outline">{outline.map(b=><button key={b.id} className={active?.id===b.id?'selected':''} style={{paddingLeft:10+b.depth*12}} onClick={()=>onSelect(b.id)}>{b.label}<small>{b.tag}</small></button>)}</div>
 {!outline.length&&<p>No HTML blocks found. Add a block to an HTML page with a main or body element.</p>}
 {active&&<div className="block-form"><label>Block name<input value={active.label} onChange={e=>edit(()=>renameBlock(source,active.id,e.target.value))}/></label><div className="element-actions"><button onClick={()=>{edit(()=>moveElement(source,active.id,'up'));onSelect(-1);}}>Move up</button><button onClick={()=>{edit(()=>moveElement(source,active.id,'down'));onSelect(-1);}}>Move down</button><button onClick={()=>edit(()=>duplicateBlock(source,active.id))}>Duplicate</button><button onClick={()=>{edit(()=>removeElement(source,active.id));onSelect(-1);}}>Remove</button></div><h3>Content</h3>{blockFields(source,active.id).slice(0,60).map(f=><label key={f.id}>{f.label}<textarea rows={2} value={f.value} onChange={e=>edit(()=>f.kind==='alt'?setElementAttribute(source,f.id,'alt',e.target.value):replaceElementText(source,f.id,e.target.value))}/></label>)}<p>Nested rich text and custom scripts remain editable in Source.</p></div>}
 </section>;
}
export function EffectsGallery({project,page,selected,onChange,onClose,onError}:{project:SiteProject;page:string;selected:number|null;onChange:(files:Record<string,string>)=>void;onClose:()=>void;onError:(message:string)=>void}){
 const [scope,setScope]=useState<'site'|'page'|'block'>('page');
 const [category,setCategory]=useState('All'),[search,setSearch]=useState('');
 const source=project.files[page]??'',bodyId=sourceNodes(source).findIndex(n=>n.tagName==='body'),block=blocks(source).find(b=>b.id===selected);
 const [chosen,setChosen]=useState<string[]>(effectValues(source,bodyId));
 const switchScope=(scope:'site'|'page'|'block')=>{setScope(scope);setChosen(effectValues(source,scope==='block'?selected??-1:bodyId,scope==='site'));};
 return <><p className="eyebrow">LOCAL CSS + JAVASCRIPT</p><h1>Special Effects</h1><p>Add atmosphere without changing your content. Motion respects the visitor’s reduced-motion setting; pointer lights are disabled on touch screens.</p><label>Apply to<select value={scope} onChange={e=>switchScope(e.target.value as typeof scope)}><option value="site">All current HTML pages</option><option value="page">This page</option><option value="block" disabled={!block}>Selected block{block?`: ${block.label}`:''}</option></select></label><p>Site and page effects combine. To remove an inherited site effect, choose All current HTML pages. New pages are not included automatically.</p><div className="gallery-filters"><input aria-label="Search effects" placeholder="Search effects…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Effect category" value={category} onChange={e=>setCategory(e.target.value)}>{['All',...new Set(effects.map(e=>e.category))].map(c=><option key={c}>{c}</option>)}</select></div><div className="effects-grid">{effects.filter(e=>(category==='All'||e.category===category)&&e.name.toLowerCase().includes(search.toLowerCase())).map(effect=>{const disabled=scope!=='block'&&'onlyBlock'in effect;return <label key={effect.id} className={`effect-card ${disabled?'unavailable':''}`}><input type="checkbox" checked={chosen.includes(effect.id)} disabled={disabled} onChange={e=>setChosen(current=>e.target.checked?[...current,effect.id]:current.filter(id=>id!==effect.id))}/><strong>{effect.name}</strong><small>{effect.category}{disabled?' · block only':''}</small></label>;})}</div><p>Pointer glow and spotlight use a decorative overlay. Preview your page’s contrast before exporting. Background effects share the background layer; choose one background treatment.</p><button onClick={()=>setChosen([])}>Clear this scope</button><button className="primary" disabled={scope==='block'&&!block} onClick={()=>{try{onChange(applyEffects(project,page,scope,chosen,selected));onClose();}catch(e){onError(String(e));}}}>Apply effects</button></>;
}

