import {selectionBox,marqueeHits,type MarqueeCandidate} from './marquee';
import {createContextMenu} from './context-menu';
import {resizeGeometry,translationParts,keyboardNudge} from './resize-geometry';
import type {CopyItem} from './element-clipboard';
import {snapMovement,type SnapGuide} from './snapping';
import type {CanvasEdit} from './canvas-edit';
export function attachSelection(doc:Document,options:{selectedTokens?:string[];snapping?:boolean;drawing?:boolean;onFollowLink?:(href:string)=>void;tool:'select'|'move'|'resize'|'rotate';onEdit:(edit:CanvasEdit)=>void;onSelect:(id:number)=>void;onError:(message:string)=>void;onDeselect?:()=>void;onCopy?:(items:CopyItem[])=>string|void;onPaste?:(point?:{x:number;y:number},origin?:{x:number;y:number})=>void;canPaste?:()=>boolean;clipboardText?:()=>string}){
 const win=doc.defaultView;if(!win)return()=>{};
 const layer=doc.createElement('div');layer.setAttribute('data-webbit-overlay','');layer.style.cssText='all:initial;position:fixed;inset:0;pointer-events:none;z-index:2147483647';doc.body.append(layer);
 const visuals=doc.createElement('div');visuals.style.cssText='all:initial;position:fixed;inset:0;pointer-events:none;z-index:1';layer.append(visuals);
 const marked=Array.from(doc.querySelectorAll<HTMLElement>('[data-webbit-canvas-selected]'));
 let selected:HTMLElement[]=marked.length?marked:Array.from(doc.querySelectorAll<HTMLElement>('[data-wb-canvas-id]')).filter(el=>options.selectedTokens?.includes(el.getAttribute('data-wb-canvas-id')!)),editing:HTMLElement|null=null;
 type Item={el:HTMLElement;id:number;x:number;y:number;width:number;height:number;rotation:number;originalStyle:string|null;resizeCss?:string};
 let gesture:{kind:'move'|'resize'|'rotate';x:number;y:number;scrollY:number;items:Item[];handle:string;moved:boolean;cx:number;cy:number;angle:number;link?:string}|null=null;
 let pointer={x:0,y:0},raf=0;
 let marquee:{start:{x:number;y:number};before:HTMLElement[];add:boolean;capture:HTMLElement;pointerId:number;cursor:string;targets:HTMLElement[]}|null=null,marqueeFrame=0,suppressClick=false;
 const marqueeBox=doc.createElement('div');marqueeBox.dataset.webbitMarquee='';marqueeBox.style.cssText='all:initial;position:fixed;pointer-events:none;z-index:3;border:1px solid #bca8ff;background:#9063ff22;box-sizing:border-box';
 const identify=(el:HTMLElement)=>Number(el.getAttribute('data-webbit-node'));
 const refresh=()=>{doc.querySelectorAll('[data-webbit-canvas-selected]').forEach(el=>el.removeAttribute('data-webbit-canvas-selected'));selected.forEach(el=>el.setAttribute('data-webbit-canvas-selected',''));visuals.replaceChildren();if(selected.length){const badge=doc.createElement('button');badge.type='button';badge.setAttribute('data-delete-selection','');badge.textContent=`Delete ${selected.length} selected`;badge.title='Shift-click to select more. Drag to move. Ctrl-drag to rotate. Double-click text to edit.';badge.style.cssText='all:initial;position:fixed;right:18px;top:8px;padding:8px 12px;background:#30234d;color:white;font:13px Arial;border-radius:5px;pointer-events:auto;cursor:pointer';visuals.append(badge);}for(const el of selected){if(!el.isConnected)continue;const r=el.getBoundingClientRect(),box=doc.createElement('div');box.style.cssText=`all:initial;position:fixed;left:${r.left-6}px;top:${r.top-6}px;width:${r.width+12}px;height:${r.height+12}px;border:2px solid #9063ff;box-sizing:border-box;pointer-events:none;`;visuals.append(box);for(const [name,x,y]of [['nw',0,0],['n',50,0],['ne',100,0],['e',100,50],['se',100,100],['s',50,100],['sw',0,100],['w',0,50]] as const){const h=doc.createElement('button');h.type='button';h.setAttribute('aria-label',`Resize ${el.tagName.toLowerCase()} ${name}`);h.dataset.handle=name;h.dataset.node=String(identify(el));h.style.cssText=`all:initial;position:absolute;left:${x}%;top:${y}%;transform:translate(-50%,-50%);width:10px;height:10px;background:white;border:2px solid #7955da;pointer-events:auto;cursor:${name}-resize;`;box.append(h);}}};
 const stopText=()=>{if(editing){editing.removeAttribute('contenteditable');if(editing.hasAttribute('data-webbit-text-index')){const parent=editing.parentElement;editing.replaceWith(...Array.from(editing.childNodes));parent?.normalize();}editing=null;}};
 const textAt=(x:number,y:number,target:Element)=>{if(target.closest('[data-webbit-overlay],script,style,textarea,input,select,svg'))return null;const walker=doc.createTreeWalker(target,4);let node:Node|null;while((node=walker.nextNode())){if(!node.textContent?.trim()||!node.parentElement?.hasAttribute('data-webbit-node'))continue;const range=doc.createRange();range.selectNodeContents(node);if(Array.from(range.getClientRects()).some(r=>x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom))return node as Text;}return null;};
 const beginText=(text:Text,x?:number,y?:number)=>{stopText();const parent=text.parentElement;if(!parent)return;const index=Array.from(parent.childNodes).filter(n=>n.nodeType===3).indexOf(text);if(index<0)return;select(pick(parent)??parent,false);const span=doc.createElement('span');span.dataset.webbitTextIndex=String(index);span.dataset.webbitTextParent=String(identify(parent));span.style.cssText='display:inline;min-width:1px;outline:1px dashed #269887';text.replaceWith(span);span.append(text);editing=span;span.contentEditable='plaintext-only';span.tabIndex=0;span.focus({preventScroll:true});const range=(x!==undefined&&y!==undefined?doc.caretRangeFromPoint(x,y):null)??doc.createRange();if(!span.contains(range.startContainer)){range.selectNodeContents(span);range.collapse(false);}const selection=win.getSelection();selection?.removeAllRanges();selection?.addRange(range);};
 doc.querySelectorAll('[contenteditable]').forEach(el=>el.removeAttribute('contenteditable'));
 const pick=(target:Element)=>target.closest<HTMLElement>('[data-wb-group][data-webbit-node]')??target.closest<HTMLElement>('button[data-webbit-node],a[data-webbit-node],svg[data-webbit-node],video[data-webbit-node],audio[data-webbit-node]')??target.closest<HTMLElement>('[data-webbit-node]');
 const members=(el:HTMLElement)=>{const group=el.getAttribute('data-wb-group');return group?Array.from(doc.querySelectorAll<HTMLElement>('[data-wb-group]')).filter(e=>e.getAttribute('data-wb-group')===group):[el];};
 const select=(el:HTMLElement,add:boolean,notify=true)=>{const group=members(el);if(add){selected=group.every(e=>selected.includes(e))?selected.filter(e=>!group.includes(e)):[...selected.filter(e=>!group.some(g=>e.contains(g)||g.contains(e))),...group];}else if(!selected.includes(el))selected=group;refresh();if(notify){if(selected.length)options.onSelect(identify(selected[selected.length-1]));else options.onDeselect?.();}};
 const items=():Item[]=>selected.map(el=>{const r=el.getBoundingClientRect(),s=win.getComputedStyle(el);return {el,id:identify(el),x:r.x+(r.width-(el.offsetWidth||r.width))/2,y:r.y+(r.height-(el.offsetHeight||r.height))/2,width:el.offsetWidth||r.width,height:el.offsetHeight||r.height,rotation:parseFloat(s.rotate)||0,originalStyle:el.getAttribute('style')};});
 const marqueeUpdate=()=>{if(!marquee)return;const rect=selectionBox(marquee.start,{x:pointer.x+win.scrollX,y:pointer.y+win.scrollY});
 const candidates:MarqueeCandidate[]=marquee.targets.filter(el=>el.isConnected&&win.getComputedStyle(el).visibility!=='hidden'&&win.getComputedStyle(el).display!=='none').map(el=>{const r=el.getBoundingClientRect();return {id:identify(el),parent:el.parentElement?.closest('[data-webbit-node]')?Number(el.parentElement.closest('[data-webbit-node]')!.getAttribute('data-webbit-node')):null,box:{x:r.x+win.scrollX,y:r.y+win.scrollY,width:r.width,height:r.height},group:el.getAttribute('data-wb-group')};});
 const ids=marqueeHits(candidates,rect,marquee.add?marquee.before.map(identify):[]),next=marquee.targets.filter(el=>ids.includes(identify(el)));
 if(next.length!==selected.length||next.some((el,i)=>el!==selected[i])){selected=next;refresh();}
 Object.assign(marqueeBox.style,{left:(rect.x-win.scrollX)+'px',top:(rect.y-win.scrollY)+'px',width:rect.width+'px',height:rect.height+'px'});};
 const marqueeTick=()=>{if(!marquee)return;const moved=Math.hypot(pointer.x+win.scrollX-marquee.start.x,pointer.y+win.scrollY-marquee.start.y)>4;if(moved){const speed=pointer.y<32?-12:pointer.y>win.innerHeight-32?12:0;if(speed)win.scrollBy(0,speed);}marqueeUpdate();marqueeFrame=win.requestAnimationFrame(marqueeTick);};
 const finishMarquee=(abort=false)=>{if(!marquee)return;const state=marquee;const moved=Math.hypot(pointer.x+win.scrollX-state.start.x,pointer.y+win.scrollY-state.start.y)>4;if(!abort&&moved)marqueeUpdate();else selected=state.before;marquee=null;win.cancelAnimationFrame(marqueeFrame);marqueeBox.remove();doc.body.style.cursor=state.cursor;try{if(state.capture.hasPointerCapture(state.pointerId))state.capture.releasePointerCapture(state.pointerId);}catch{}refresh();if(!abort){suppressClick=true;if(selected.length)options.onSelect(identify(selected[selected.length-1]));else options.onDeselect?.();}};
 const startMarquee=(e:PointerEvent)=>{cancel();stopText();win.getSelection()?.removeAllRanges();layer.querySelector('[role=menu]')?.remove();doc.body.tabIndex=-1;doc.body.focus({preventScroll:true});
 const targets=Array.from(new Set(Array.from(doc.querySelectorAll<HTMLElement>('[data-webbit-node]')).filter(el=>!['HTML','HEAD','BODY','MAIN','SCRIPT','STYLE','LINK','META','TITLE','BASE'].includes(el.tagName)&&!el.closest('[data-webbit-overlay]')).map(pick).filter(Boolean))) as HTMLElement[];
 marquee={start:{x:e.clientX+win.scrollX,y:e.clientY+win.scrollY},before:[...selected],add:e.shiftKey,capture:doc.documentElement,pointerId:e.pointerId,cursor:doc.body.style.cursor,targets};pointer={x:e.clientX,y:e.clientY};doc.body.style.cursor='crosshair';layer.append(marqueeBox);try{marquee.capture.setPointerCapture?.(e.pointerId);}catch{}marqueeFrame=win.requestAnimationFrame(marqueeTick);};
 const down=(e:PointerEvent)=>{if(e.button!==0)return;suppressClick=false;const t=e.target as Element;if(e.altKey&&!t.closest('[role=menu],[data-delete-selection]')){e.preventDefault();e.stopImmediatePropagation();startMarquee(e);return;}if(options.drawing)return;if(t.closest('[data-delete-selection],[role=menu],[data-layer-action]'))return;layer.querySelector('[role=menu]')?.remove();if(editing?.contains(t)&&!e.ctrlKey&&!e.shiftKey)return;stopText();const handle=t.closest<HTMLElement>('[data-handle]');const el=handle?doc.querySelector<HTMLElement>(`[data-webbit-node="${handle.dataset.node}"]`):pick(t);if(!el||['HTML','BODY'].includes(el.tagName)||(el.tagName==='MAIN'&&t===el&&!e.shiftKey&&!e.ctrlKey&&options.tool==='select')){e.preventDefault();e.stopImmediatePropagation();clearSelection();doc.body.tabIndex=-1;doc.body.focus({preventScroll:true});return;}if(['HEAD','SCRIPT','STYLE','LINK','META','TITLE'].includes(el.tagName))return;
 if(!handle&&!el.hasAttribute('data-wb-group')&&!e.ctrlKey&&!e.shiftKey&&options.tool==='select'){const text=textAt(e.clientX,e.clientY,t);if(text){e.preventDefault();e.stopImmediatePropagation();beginText(text,e.clientX,e.clientY);return;}}
 e.preventDefault();e.stopImmediatePropagation();doc.body.tabIndex=-1;doc.body.focus({preventScroll:true});if(e.shiftKey&&!handle){select(el,true);return;}select(el,false,false);const list=items(),minX=Math.min(...list.map(i=>i.x)),minY=Math.min(...list.map(i=>i.y)),maxX=Math.max(...list.map(i=>i.x+i.width)),maxY=Math.max(...list.map(i=>i.y+i.height));const cx=(minX+maxX)/2,cy=(minY+maxY)/2;
 gesture={kind:e.ctrlKey||options.tool==='rotate'?'rotate':handle||options.tool==='resize'?'resize':'move',x:e.clientX,y:e.clientY,scrollY:win.scrollY,items:list,handle:handle?.dataset.handle??'se',moved:false,cx,cy,angle:Math.atan2(e.clientY-cy,e.clientX-cx),link:e.ctrlKey&&!e.shiftKey?t.closest('a[href]')?.getAttribute('href')??undefined:undefined};pointer={x:e.clientX,y:e.clientY};el.setPointerCapture?.(e.pointerId);raf=win.requestAnimationFrame(tick);};
 let guides:SnapGuide[]=[];
 const delta=()=>{const g=gesture!,dx=pointer.x-g.x,dy=pointer.y-g.y+win.scrollY-g.scrollY;guides=[];if(g.kind!=='move'||options.snapping===false)return {dx,dy};
  const left=Math.min(...g.items.map(i=>i.x)),top=Math.min(...g.items.map(i=>i.y))+g.scrollY;
  const box={x:left,y:top,width:Math.max(...g.items.map(i=>i.x+i.width))-left,height:Math.max(...g.items.map(i=>i.y+i.height))+g.scrollY-top};
  const targets=[{box:{x:0,y:0,width:doc.documentElement.clientWidth,height:Math.max(doc.body.scrollHeight,doc.documentElement.clientHeight)},label:'Page'}];
  for(const el of Array.from(doc.querySelectorAll<HTMLElement>('[data-webbit-node]'))){if(['HTML','HEAD','BODY','SCRIPT','STYLE','LINK','META'].includes(el.tagName)||g.items.some(i=>i.el.contains(el)||el.contains(i.el)))continue;const r=el.getBoundingClientRect();if(!r.width||!r.height||r.bottom<0||r.top>win.innerHeight)continue;targets.push({box:{x:r.x,y:r.y+win.scrollY,width:r.width,height:r.height},label:el.tagName.toLowerCase()+(el.id?' #'+el.id:'')});}
  const snap=snapMovement(box,dx,dy,targets);guides=snap.guides;return snap;
 };
 const drawGuides=()=>{for(const guide of guides){const vertical=guide.axis==='x',line=doc.createElement('div');line.dataset.snapGuide=guide.axis;line.style.cssText=`all:initial;position:fixed;pointer-events:none;${vertical?`left:${guide.value}px;top:20px;bottom:0;border-left:1px solid #ff6eac`:`top:${guide.value-win.scrollY}px;left:20px;right:0;border-top:1px solid #ff6eac`}`;const label=doc.createElement('span');label.textContent=guide.label;label.style.cssText='all:initial;position:absolute;left:4px;top:4px;white-space:nowrap;background:#502340;color:#fff;font:11px Arial;padding:3px 5px;border-radius:3px';line.append(label);visuals.append(line);}};
 const restore=(i:Item)=>{if(i.originalStyle===null)i.el.removeAttribute('style');else i.el.setAttribute('style',i.originalStyle);};
 const resizeItem=(i:Item,dx:number,dy:number)=>{restore(i);const style=win.getComputedStyle(i.el),parts=translationParts(style.translate);const n=(v:string)=>parseFloat(v)||0;const floorW=n(style.paddingLeft)+n(style.paddingRight)+n(style.borderLeftWidth)+n(style.borderRightWidth),floorH=n(style.paddingTop)+n(style.paddingBottom)+n(style.borderTopWidth)+n(style.borderBottomWidth);const r=resizeGeometry(i.width,i.height,gesture!.handle,dx,dy,Math.max(1,floorW),Math.max(1,floorH));const display=style.display==='inline'?'inline-block':style.display;
  const css=`width:${r.width}px;height:${r.height}px;box-sizing:border-box;min-width:0;min-height:0;max-width:none;max-height:none;display:${display}${i.el.tagName==='IMG'&&style.objectFit==='fill'?';object-fit:contain':''}`;
  i.el.style.cssText=(i.originalStyle??'')+';'+css;const bounds=i.el.getBoundingClientRect();const tx=i.x+r.x-bounds.left,ty=i.y+r.y-(win.scrollY-gesture!.scrollY)-bounds.top;
  i.resizeCss=css+`;translate:calc(${parts[0]} + ${Math.round(tx*100)/100}px) calc(${parts[1]} + ${Math.round(ty*100)/100}px)`;i.el.style.cssText=(i.originalStyle??'')+';'+i.resizeCss;
  return i.el.getBoundingClientRect();
 };
 const tick=()=>{if(!gesture)return;if(gesture.kind==='move'&&gesture.moved){const edge=44;const speed=pointer.y<edge?-18:pointer.y>win.innerHeight-edge?18:0;if(speed)win.scrollBy(0,speed);}if(gesture.moved){const {dx,dy}=delta();visuals.replaceChildren();for(const i of gesture.items){const b=doc.createElement('div');b.style.cssText=`all:initial;position:fixed;pointer-events:none;border:2px dashed #9063ff;box-sizing:border-box;left:${i.x+dx}px;top:${i.y+dy-(win.scrollY-gesture.scrollY)}px;width:${i.width}px;height:${i.height}px;background:#7955da22`;if(gesture.kind==='rotate'){b.style.left=i.x+'px';b.style.top=i.y+'px';b.style.rotate=angle()+'deg';}if(gesture.kind==='resize'){const r=resizeItem(i,dx,dy);b.style.left=(r.left-6)+'px';b.style.top=(r.top-6)+'px';b.style.width=(r.width+12)+'px';b.style.height=(r.height+12)+'px';}visuals.append(b);}if(gesture.kind==='move')drawGuides();}raf=win.requestAnimationFrame(tick);};
 const angle=()=>{const g=gesture!;return (Math.atan2(pointer.y-g.cy,pointer.x-g.cx)-g.angle)*180/Math.PI;};
 const move=(e:PointerEvent)=>{if(marquee){pointer={x:e.clientX,y:e.clientY};e.preventDefault();e.stopImmediatePropagation();return;}if(!gesture)return;pointer={x:e.clientX,y:e.clientY};if(Math.hypot(e.clientX-gesture.x,e.clientY-gesture.y)>4)gesture.moved=true;e.preventDefault();};
 const cancel=()=>{finishMarquee(true);if(gesture?.kind==='resize')gesture.items.forEach(restore);gesture=null;win.cancelAnimationFrame(raf);refresh();};
 const clearSelection=()=>{stopText();selected=[];layer.querySelector('[role=menu]')?.remove();win.getSelection()?.removeAllRanges();cancel();options.onDeselect?.();};
 const up=(e:PointerEvent)=>{if(marquee){pointer={x:e.clientX,y:e.clientY};e.preventDefault();e.stopImmediatePropagation();finishMarquee();return;}if(!gesture)return;const g=gesture;pointer={x:e.clientX,y:e.clientY};e.preventDefault();e.stopImmediatePropagation();try{if(!g.moved){if(g.link!==undefined){clearSelection();options.onFollowLink?.(g.link);}else if(g.items.length)options.onSelect(g.items[g.items.length-1].id);}if(g.moved){const {dx,dy}=delta();if(g.kind==='rotate')options.onEdit({kind:'style',items:g.items.map(i=>({id:i.id,css:`rotate:${Math.round((i.rotation+angle())*10)/10}deg;transform-origin:center;display:${win.getComputedStyle(i.el).display==='inline'?'inline-block':win.getComputedStyle(i.el).display}`}))});else if(g.kind==='resize'){const changes=g.items.map(i=>{resizeItem(i,dx,dy);return {id:i.id,css:i.resizeCss!};});g.items.forEach(restore);options.onEdit({kind:'style',items:changes});}else{
 const hit=doc.elementsFromPoint(e.clientX,e.clientY).find(el=>!layer.contains(el)&&!g.items.some(i=>i.el.contains(el)));let parent=hit?.closest<HTMLElement>('section[data-webbit-node],article[data-webbit-node],div[data-webbit-node],header[data-webbit-node],footer[data-webbit-node],main[data-webbit-node],body[data-webbit-node],aside[data-webbit-node],nav[data-webbit-node],form[data-webbit-node],li[data-webbit-node],td[data-webbit-node]')??doc.body;
 const parentStyle=parent.getAttribute('style');parent.style.position='relative';for(const i of g.items){i.el.style.position='absolute';i.el.style.margin='0';}const r=parent.getBoundingClientRect();g.items.forEach(restore);if(parentStyle===null)parent.removeAttribute('style');else parent.setAttribute('style',parentStyle);options.onEdit({kind:'move',parent:identify(parent),items:g.items.map(i=>({id:i.id,rect:{x:i.x+dx-r.x+parent.scrollLeft-parent.clientLeft,y:i.y+dy-(win.scrollY-g.scrollY)-r.y+parent.scrollTop-parent.clientTop,width:i.width,height:i.height}}))});}}}catch(error){options.onError(String(error));}finally{cancel();}};
 const click=(e:MouseEvent)=>{if(suppressClick){suppressClick=false;e.preventDefault();e.stopImmediatePropagation();return;}if(options.drawing)return;if((e.target as Element).closest('[role=menu]'))return;const action=(e.target as Element).closest<HTMLElement>('[data-layer-action]');if(action){e.preventDefault();e.stopImmediatePropagation();layer.querySelector('[role=menu]')?.remove();layerAction(action.dataset.layerAction!);return;}if((e.target as Element).closest('[data-delete-selection]')){e.preventDefault();e.stopImmediatePropagation();options.onEdit({kind:'delete',ids:selected.map(identify)});clearSelection();return;}if(editing?.contains(e.target as Node)){e.stopImmediatePropagation();if((e.target as Element).closest('a,button'))e.preventDefault();return;}e.preventDefault();e.stopImmediatePropagation();};
 const dbl=(e:MouseEvent)=>{if(editing?.contains(e.target as Node))return;const target=(e.target as Element).closest<HTMLElement>('[data-webbit-node]');if(!target||target.closest('[data-webbit-overlay]'))return;const direct=Array.from(target.childNodes).find(n=>n.nodeType===3&&n.textContent?.trim()) as Text|undefined;const text=textAt(e.clientX,e.clientY,target)??direct;if(text){e.preventDefault();e.stopImmediatePropagation();beginText(text,e.clientX,e.clientY);}};
 const copy=()=>{stopText();try{return options.onCopy?.(items().map(i=>({id:i.id,rect:{x:i.x+win.scrollX,y:i.y+win.scrollY,width:i.width,height:i.height}})));}catch(error){options.onError(String(error));}};
 const paste=(point?:{x:number;y:number})=>{stopText();const r=doc.body.getBoundingClientRect(),position=win.getComputedStyle(doc.body).position;const origin=position==='static'?{x:0,y:0}:{x:r.left+win.scrollX+doc.body.clientLeft,y:r.top+win.scrollY+doc.body.clientTop};options.onPaste?.(point,origin);};
 const center=()=>{stopText();if(!selected.length)return;const rects=selected.map(el=>el.getBoundingClientRect()),left=Math.min(...rects.map(r=>r.left)),right=Math.max(...rects.map(r=>r.right));const dx=doc.documentElement.clientWidth/2-(left+right)/2;options.onEdit({kind:'style',items:selected.map(el=>{const style=win.getComputedStyle(el),parts=translationParts(style.translate);return {id:identify(el),css:`translate:calc(${parts[0]||'0px'} + ${Math.round(dx*100)/100}px) ${parts[1]||'0px'};display:${style.display==='inline'?'inline-block':style.display}`};})});};
 const context=(e:MouseEvent)=>{cancel();layer.querySelector('[role=menu]')?.remove();const el=pick(e.target as Element);e.preventDefault();e.stopImmediatePropagation();stopText();if(el&&!['BODY','HTML','HEAD'].includes(el.tagName))select(el,false);else clearSelection();
  const controls=createContextMenu(doc,layer,{x:e.clientX,y:e.clientY},'Element actions'),{menu,add}=controls;
  add(menu,'Copy elements (Ctrl+C)',()=>{copy();menu.remove();},!selected.length);
  add(menu,'Paste elements (Ctrl+V)',()=>{menu.remove();paste({x:e.clientX+win.scrollX,y:e.clientY+win.scrollY});},!options.canPaste?.());
  add(menu,'Group selected',()=>{menu.remove();options.onEdit({kind:'group',ids:selected.map(identify)});},selected.length<2||selected.every(el=>el.getAttribute('data-wb-group')&&el.getAttribute('data-wb-group')===selected[0].getAttribute('data-wb-group')));
  add(menu,'Ungroup selected',()=>{menu.remove();options.onEdit({kind:'ungroup',ids:selected.map(identify)});},!selected.some(el=>el.hasAttribute('data-wb-group')));
  add(menu,'Center horizontally on page',()=>{menu.remove();center();},!selected.length);
  const position=add(menu,'Position >',()=>{const old=menu.querySelector('[aria-label="Position"]');if(old){old.remove();position.setAttribute('aria-expanded','false');return;}const submenu=doc.createElement('div');submenu.setAttribute('role','menu');submenu.setAttribute('aria-label','Position');submenu.style.cssText='all:initial;display:block;margin:2px 0 4px 10px;padding-left:5px;border-left:2px solid #8f7abd';position.after(submenu);position.setAttribute('aria-expanded','true');menu.style.top=Math.max(4,Math.min(e.clientY,win.innerHeight-445))+'px';for(const [action,label]of [['front','Bring to front'],['forward','Bring forward'],['backward','Send backward'],['back','Send to back']])add(submenu,label,()=>{menu.remove();layerAction(action);});},!selected.length);position.setAttribute('aria-haspopup','menu');position.setAttribute('aria-expanded','false');
  add(menu,'Delete selected',()=>{menu.remove();options.onEdit({kind:'delete',ids:selected.map(identify)});clearSelection();},!selected.length);
  controls.fit();menu.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus({preventScroll:true});
  menu.addEventListener('keydown',event=>{const current=event.target as HTMLButtonElement;const buttons=Array.from(menu.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));const index=buttons.indexOf(current);if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(event.key==='ArrowRight'&&current===position){event.preventDefault();if(position.getAttribute('aria-expanded')==='false')position.click();menu.querySelector<HTMLButtonElement>('[aria-label="Position"] button')?.focus();}if(event.key==='ArrowLeft'&&current.closest('[aria-label="Position"]')){event.preventDefault();menu.querySelector('[aria-label="Position"]')?.remove();position.setAttribute('aria-expanded','false');position.focus();}});
 };
 const layerAction=(action:string)=>{const changes:{id:number;css:string}[]=[];for(const parent of new Set(selected.map(el=>el.parentElement).filter(Boolean))){const siblings=Array.from(parent!.children).filter(el=>el.hasAttribute('data-webbit-node')&&!['SCRIPT','STYLE','LINK','META','TITLE','BASE'].includes(el.tagName)) as HTMLElement[];const sorted=siblings.map((el,index)=>({el,index,z:parseInt(win.getComputedStyle(el).zIndex)||0})).sort((a,b)=>a.z-b.z||a.index-b.index).map(i=>i.el);const chosen=sorted.filter(el=>selected.includes(el));let order=sorted;
  if(action==='front')order=[...sorted.filter(el=>!chosen.includes(el)),...chosen];else if(action==='back')order=[...chosen,...sorted.filter(el=>!chosen.includes(el))];else if(action==='forward'){for(let i=order.length-2;i>=0;i--)if(chosen.includes(order[i])&&!chosen.includes(order[i+1]))[order[i],order[i+1]]=[order[i+1],order[i]];}else {for(let i=1;i<order.length;i++)if(chosen.includes(order[i])&&!chosen.includes(order[i-1]))[order[i],order[i-1]]=[order[i-1],order[i]];}
  order.forEach((el,index)=>changes.push({id:identify(el),css:`position:${win.getComputedStyle(el).position==='static'?'relative':win.getComputedStyle(el).position};z-index:${index}`}));
 }if(changes.length)options.onEdit({kind:'style',selectionIds:selected.map(identify),items:changes});};
 const closeMenu=()=>layer.querySelector('[role=menu]')?.remove();
 const outer=win.frameElement?.ownerDocument;outer?.addEventListener('pointerdown',closeMenu,true);
 const key=(e:KeyboardEvent)=>{if(marquee&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();finishMarquee(true);return;}if(e.key==='Escape'&&layer.querySelector('[role=menu]')){e.preventDefault();e.stopImmediatePropagation();closeMenu();doc.body.focus({preventScroll:true});return;}if((e.target as Element).closest('[role=menu]')){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();layer.querySelector('[role=menu]')?.remove();doc.body.focus({preventScroll:true});}return;}if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();clearSelection();return;}if(editing)return;
 const nudge=keyboardNudge(e.key,e.shiftKey,e.ctrlKey,e.altKey,e.metaKey);if(nudge&&selected.length&&!(e.target as Element).closest('[role=menu],input,textarea,select,[contenteditable]')){e.preventDefault();e.stopImmediatePropagation();const {dx,dy}=nudge;options.onEdit({kind:'style',items:selected.map(el=>{const style=win.getComputedStyle(el),parts=translationParts(style.translate);return {id:identify(el),css:`translate:calc(${parts[0]} + ${dx}px) calc(${parts[1]} + ${dy}px);display:${style.display==='inline'?'inline-block':style.display}`};})});return;}
 const key=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&!e.altKey&&(key==='c'||key==='v')){if(key==='c'&&selected.length){e.stopPropagation();}else if(key==='v'&&options.canPaste?.()){e.stopPropagation();}return;}if(e.key==='Delete'&&selected.length){e.preventDefault();e.stopImmediatePropagation();options.onEdit({kind:'delete',ids:selected.map(identify)});clearSelection();}};
 const pasteEvent=(e:ClipboardEvent)=>{if(editing||!options.canPaste?.())return;const text=e.clipboardData?.getData('text/plain')??'';if(options.clipboardText&&text.replace(/\r\n/g,'\n')!==options.clipboardText().replace(/\r\n/g,'\n'))return;e.preventDefault();e.stopImmediatePropagation();paste();};
 const copyEvent=(e:ClipboardEvent)=>{if(editing||!selected.length)return;const text=copy();if(typeof text==='string'){e.preventDefault();e.stopImmediatePropagation();e.clipboardData?.setData('text/plain',text);e.clipboardData?.setData('text/html',text);}};
 const blur=()=>{if(marquee)finishMarquee(true);};win.addEventListener('blur',blur);
 refresh();doc.addEventListener('paste',pasteEvent,true);doc.addEventListener('copy',copyEvent,true);doc.addEventListener('pointerdown',down,true);doc.addEventListener('pointermove',move,true);doc.addEventListener('pointerup',up,true);doc.addEventListener('pointercancel',cancel,true);doc.addEventListener('click',click,true);doc.addEventListener('dblclick',dbl,true);doc.addEventListener('keydown',key,true);doc.addEventListener('contextmenu',context,true);win.addEventListener('scroll',refresh,true);win.addEventListener('resize',refresh);
 return()=>{win.removeEventListener('blur',blur);outer?.removeEventListener('pointerdown',closeMenu,true);cancel();stopText();layer.remove();doc.removeEventListener('paste',pasteEvent,true);doc.removeEventListener('copy',copyEvent,true);doc.removeEventListener('pointerdown',down,true);doc.removeEventListener('pointermove',move,true);doc.removeEventListener('pointerup',up,true);doc.removeEventListener('pointercancel',cancel,true);doc.removeEventListener('click',click,true);doc.removeEventListener('dblclick',dbl,true);doc.removeEventListener('keydown',key,true);doc.removeEventListener('contextmenu',context,true);win.removeEventListener('scroll',refresh,true);win.removeEventListener('resize',refresh);};
}

