import {describe,it,expect} from 'vitest';import {editCanvas} from './canvas-edit';import {sourceNodes} from './blocks';
const s='<!doctype html><html><head><title>Keep</title></head><body><header><button>A</button><img src="a.png"></header><main><p>Text</p></main><footer><p>End</p></footer><script>keep()</script></body></html>';
const id=(tag:string)=>sourceNodes(s).findIndex(n=>n.tagName===tag);
describe('canvas group source edits',()=>{
 it('moves a header button and image to the footer together without duplicates',()=>{const out=editCanvas(s,{kind:'move',parent:id('footer'),items:[{id:id('button'),rect:{x:20,y:30,width:80,height:40}},{id:id('img'),rect:{x:130,y:50,width:90,height:90}}]});expect(out).toContain('<header></header>');expect(out.indexOf('<button')).toBeGreaterThan(out.indexOf('<footer'));expect(out.match(/<button/g)).toHaveLength(1);expect(out).toContain('left:130px;top:50px');expect(out).toContain('<script>keep()</script>');});
 it('deletes a parent and selected descendants once, preserving unrelated content',()=>{const out=editCanvas(s,{kind:'delete',ids:[id('header'),id('button'),id('img')]});expect(out).not.toContain('<header');expect(out).toContain('<main><p>Text</p></main>');});
 it('rotates and resizes multiple elements using source CSS',()=>{const out=editCanvas(s,{kind:'style',items:[{id:id('button'),css:'rotate:35deg;width:150px'},{id:id('img'),css:'rotate:35deg;width:160px'}]});expect(out.match(/rotate:35deg/g)).toHaveLength(2);expect(out).toContain('src="a.png"');});
 it('rejects document-shell deletion and moving a parent into its child',()=>{expect(()=>editCanvas(s,{kind:'delete',ids:[id('body')]})).toThrow();expect(()=>editCanvas(s,{kind:'move',parent:id('button'),items:[{id:id('header'),rect:{x:0,y:0,width:10,height:10}}]})).toThrow();});
 it('normalizes nested selections during movement and preserves source order',()=>{const out=editCanvas(s,{kind:'move',parent:id('footer'),items:[{id:id('button'),rect:{x:4,y:5,width:80,height:40}},{id:id('header'),rect:{x:2,y:3,width:300,height:100}}]});expect(out.match(/<button/g)).toHaveLength(1);expect(out.indexOf('<header')).toBeGreaterThan(out.indexOf('<footer'));});
});
