import {attachRulers} from './rulers';
import {attachSelection} from './canvas-selection';
import type {CanvasEdit} from './canvas-edit';
import {sourceElement} from './preview';
import {sourceNodes,insertMarkup} from './blocks';
import {setElementAttribute} from './inspector';
export type CanvasRect={x:number;y:number;width:number;height:number};
const styled=(source:string,id:number,extra:string)=>{const old=sourceElement(source,id)?.attrs.find(a=>a.name==='style')?.value??'';return setElementAttribute(source,id,'style',old+';'+extra);};
const geometry=(r:CanvasRect)=>{if(Object.values(r).some(v=>!Number.isFinite(v)))throw new Error('Invalid placement.');return `position:absolute;left:${Math.max(0,Math.round(r.x))}px;top:${Math.max(0,Math.round(r.y))}px;width:${Math.max(24,Math.round(r.width))}px;min-height:${Math.max(24,Math.round(r.height))}px;box-sizing:border-box;max-width:100%`;};
export function placeElement(source:string,parentId:number,markup:string,rect:CanvasRect){const parent=sourceElement(source,parentId);if(!parent||!['body','main','section','article','div','header','footer','aside','nav','figure'].includes(parent.tagName))throw new Error('Draw within a section or container.');
 const rootId=sourceNodes(markup).findIndex(n=>n.sourceCodeLocation?.startOffset===0);if(rootId<0)throw new Error('Element has no source root.');const placed=styled(markup,rootId,geometry(rect));source=styled(source,parentId,`position:relative;min-height:${Math.ceil(rect.y+rect.height+24)}px`);return insertMarkup(source,placed,parentId);
}
export function resizeElement(source:string,id:number,width:number,height:number){if(!Number.isFinite(width)||!Number.isFinite(height))throw new Error('Invalid size.');return styled(source,id,`width:${Math.max(24,Math.round(width))}px;height:${Math.max(24,Math.round(height))}px;box-sizing:border-box;max-width:100%`);}
export function relocateElement(source:string,id:number,parentId:number,rect:CanvasRect){const node=sourceElement(source,id),parent=sourceElement(source,parentId),loc=node?.sourceCodeLocation,p=parent?.sourceCodeLocation;if(!node||!loc||!p?.endTag||['html','head','body','main','script','style'].includes(node.tagName))throw new Error('Choose a movable content element.');if(p.startOffset>=loc.startOffset&&p.endOffset<=loc.endOffset)throw new Error('An element cannot be moved into itself.');
 const markup=source.slice(loc.startOffset,loc.endOffset);const parentStart=p.startOffset;const without=source.slice(0,loc.startOffset)+source.slice(loc.endOffset);const adjusted=parentStart>loc.startOffset?parentStart-(loc.endOffset-loc.startOffset):parentStart;const target=sourceNodes(without).findIndex(n=>n.sourceCodeLocation?.startOffset===adjusted);return placeElement(without,target,markup,rect);
}
function attachCanvasCore(doc:Document,options:{snapping?:boolean;onFollowLink?:(href:string)=>void;rulers?:boolean;onHideRulers?:()=>void;selectedTokens?:string[];enabled?:boolean;onEdit?:(edit:CanvasEdit)=>void;onSelect?:(id:number)=>void;tool:'select'|'move'|'resize'|'rotate';markup:string|null;onDraw:(parent:number,rect:CanvasRect)=>void;onMove:(id:number,parent:number,rect:CanvasRect)=>void;onResize:(id:number,width:number,height:number)=>void;onError:(message:string)=>void;onDeselect?:()=>void;onCopy?:Parameters<typeof attachSelection>[1]['onCopy'];onPaste?:Parameters<typeof attachSelection>[1]['onPaste'];canPaste?:()=>boolean;clipboardText?:()=>string}){
 const win=doc.defaultView;if(!win||options.enabled===false)return ()=>{};if(!options.markup&&options.onEdit)return attachSelection(doc,{onFollowLink:options.onFollowLink,onDeselect:options.onDeselect,onCopy:options.onCopy,onPaste:options.onPaste,canPaste:options.canPaste,clipboardText:options.clipboardText,snapping:options.snapping,selectedTokens:options.selectedTokens,tool:options.tool,onEdit:options.onEdit,onSelect:options.onSelect??(()=>{}),onError:options.onError});const active=!!options.markup||options.tool!=='select';if(!active)return ()=>{};doc.body.style.cursor=options.markup?'crosshair':options.tool==='move'?'move':'nwse-resize';doc.querySelectorAll('[contenteditable]').forEach(e=>e.removeAttribute('contenteditable'));
 let start:{x:number;y:number;id:number;parent:HTMLElement;bounds:DOMRect;element:HTMLElement}|null=null;let box:HTMLDivElement|null=null;
 const container=(el:Element|null)=>el?.closest<HTMLElement>('section[data-webbit-node],article[data-webbit-node],div[data-webbit-node],main[data-webbit-node],body[data-webbit-node],header[data-webbit-node],footer[data-webbit-node]')??doc.body;
 const down=(event:PointerEvent)=>{if(event.button!==0)return;const el=(event.target as Element)?.closest<HTMLElement>('[data-webbit-node]');if(!el)return;event.preventDefault();event.stopImmediatePropagation();const parent=options.markup?container(el):container(el.parentElement);start={x:event.clientX,y:event.clientY,id:Number(el.dataset.webbitNode),parent,bounds:el.getBoundingClientRect(),element:el};box=doc.createElement('div');box.style.cssText='position:fixed;pointer-events:none;z-index:2147483647;border:2px solid #7955da;background:#7955da22;';doc.body.appendChild(box);};
 const move=(event:PointerEvent)=>{if(!start||!box)return;const r=options.markup?{x:Math.min(start.x,event.clientX),y:Math.min(start.y,event.clientY),width:Math.abs(event.clientX-start.x),height:Math.abs(event.clientY-start.y)}:{x:options.tool==='move'?start.bounds.x+event.clientX-start.x:start.bounds.x,y:options.tool==='move'?start.bounds.y+event.clientY-start.y:start.bounds.y,width:options.tool==='resize'?Math.max(24,start.bounds.width+event.clientX-start.x):start.bounds.width,height:options.tool==='resize'?Math.max(24,start.bounds.height+event.clientY-start.y):start.bounds.height};Object.assign(box.style,{left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px'});};
 const up=(event:PointerEvent)=>{if(!start)return;event.preventDefault();event.stopImmediatePropagation();const state=start;start=null;box?.remove();box=null;try{
 if(options.markup){const bounds=state.parent.getBoundingClientRect();const width=Math.abs(event.clientX-state.x),height=Math.abs(event.clientY-state.y);if(width<12||height<12)return;options.onDraw(Number(state.parent.dataset.webbitNode),{x:Math.min(state.x,event.clientX)-bounds.x+state.parent.scrollLeft,y:Math.min(state.y,event.clientY)-bounds.y+state.parent.scrollTop,width,height});}
 else if(options.tool==='resize')options.onResize(state.id,state.bounds.width+event.clientX-state.x,state.bounds.height+event.clientY-state.y);
 else{let target=container(doc.elementFromPoint(event.clientX,event.clientY));if(state.element.contains(target))target=state.parent;const bounds=target.getBoundingClientRect();options.onMove(state.id,Number(target.dataset.webbitNode),{x:event.clientX-bounds.x-(state.x-state.bounds.x)+target.scrollLeft,y:event.clientY-bounds.y-(state.y-state.bounds.y)+target.scrollTop,width:state.bounds.width,height:state.bounds.height});}
 }catch(e){options.onError(String(e));}};
 const cancel=()=>{start=null;box?.remove();box=null;};
 const selectionCleanup=options.onEdit?attachSelection(doc,{...options,drawing:true,onEdit:options.onEdit,onSelect:options.onSelect??(()=>{})}):()=>{};
 doc.addEventListener('pointerdown',down,true);doc.addEventListener('pointermove',move,true);doc.addEventListener('pointerup',up,true);doc.addEventListener('pointercancel',cancel,true);
 return ()=>{selectionCleanup();cancel();doc.body.style.cursor='';doc.removeEventListener('pointerdown',down,true);doc.removeEventListener('pointermove',move,true);doc.removeEventListener('pointerup',up,true);doc.removeEventListener('pointercancel',cancel,true);};
}

export function attachCanvas(doc:Document,options:Parameters<typeof attachCanvasCore>[1]){const cleanup=attachCanvasCore(doc,options);const rulerCleanup=options.rulers!==false&&options.enabled!==false?attachRulers(doc,options.onHideRulers):()=>{};return()=>{cleanup();rulerCleanup();};}
