import React,{useState} from 'react';
import {parseData,dataMarkup,type DataTable} from './data';
import {insertMarkup} from './blocks';
import {withEnhancements} from './effects';
import type {SiteProject} from './project';
export function DataImport({project,page,onChange,onClose}:{project:SiteProject;page:string;onChange:(files:Record<string,string>)=>void;onClose:()=>void}){
 const [table,setTable]=useState<DataTable|null>(null),[columns,setColumns]=useState<number[]>([]),[limit,setLimit]=useState(100),[error,setError]=useState('');
 return <><h1>Import table data</h1><p>Import CSV, TSV or a JSON array of objects. Review your data and explicitly choose the columns to put on the public page. This produces a snapshot, not a live database connection.</p><input type="file" accept=".csv,.tsv,.json" aria-label="Choose data file" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2_000_000)throw new Error('Maximum file size: 2 MB.');const next=parseData(f.name,await f.text());setTable(next);setColumns([]);setError('');}catch(err){setError(String(err));setTable(null);}}}/>{error&&<p role="alert">{error}</p>}{table&&<><h2>{table.name}</h2><p>{table.rows.length} rows · {table.columns.length} columns. No columns are public until selected below.</p><div className="effects-grid">{table.columns.map((c,i)=><label key={i}><input type="checkbox" checked={columns.includes(i)} onChange={e=>setColumns(current=>e.target.checked?[...current,i]:current.filter(n=>n!==i))}/>{c}</label>)}</div><div style={{overflow:'auto',maxHeight:240}}><table><thead><tr>{table.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{table.rows.slice(0,10).map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c.slice(0,200)}</td>)}</tr>)}</tbody></table></div><p>Preview shows the first 10 rows.</p><label>Rows to publish<input type="number" min={1} max={2000} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><button onClick={()=>{const path=`private/data/import-${Date.now()}.json`;onChange({...project.files,[path]:JSON.stringify(table,null,2)});onClose();}}>Keep private snapshot only</button><button className="primary" disabled={!columns.length||!Number.isInteger(limit)||limit<1||limit>2000} onClick={()=>{try{const source=insertMarkup(project.files[page]??'',dataMarkup(table,columns,limit));onChange(withEnhancements({...project.files,[page]:source},page));onClose();}catch(err){setError(String(err));}}}>Insert selected data as public table</button></>}<p>SQLite and SQL dump browsing are not available in this version. Whole-site import preserves database files privately; it never executes SQL.</p></>;
}
