import {TableRibbon} from './TableRibbon';

import {MenuRibbon} from './MenuRibbon';

import React,{useEffect,useState} from 'react';

import {sourceElement} from './preview';

import {sourceNodes} from './blocks';

import {setElementAttribute,removeElementAttribute,removeElement,moveElement} from './inspector';

import {updateStyle} from './StyleControls';

import {elementStates,elementRules,updateElementRules,elementPresets,replaceElementMarkup,type ElementState} from './element-styles';

const typeAttrs:Record<string,string[]>={button:['type','name','value','form','formaction','formmethod'],a:['href','target','rel','download'],img:['src','alt','width','height','loading'],input:['type','name','value','placeholder','min','max','step','pattern','autocomplete','form'],textarea:['name','placeholder','rows','cols','maxlength'],select:['name','size','form'],option:['value','label'],form:['action','method','enctype','target','autocomplete'],video:['src','poster','preload','width','height'],audio:['src','preload'],source:['src','type','media','srcset'],iframe:['src','title','loading','allow','sandbox','width','height'],label:['for'],td:['colspan','rowspan','headers'],th:['colspan','rowspan','scope'],ol:['start','type'],li:['value'],script:['src','type'],link:['href','rel','media'],meta:['name','content'],svg:['viewBox','preserveAspectRatio','width','height','fill','stroke'],path:['d','fill','stroke','stroke-width']};

const boolAttrs:Record<string,string[]>={button:['disabled'],input:['disabled','required','readonly','checked','multiple'],textarea:['disabled','required','readonly'],select:['disabled','required','multiple'],option:['disabled','selected'],video:['controls','autoplay','muted','loop'],audio:['controls','autoplay','muted','loop'],details:['open'],form:['novalidate']};

const styleGroups:Record<string,string[]>={Typography:['font-family','font-size','font-weight','font-style','line-height','letter-spacing','text-align','text-decoration','text-transform','color','text-shadow'],Background:['background-color','background-image','background-size','background-position','background-repeat','opacity'],Borders:['border','border-radius','outline','outline-offset','box-shadow'],Layout:['display','position','width','height','min-width','max-width','min-height','max-height','padding','margin','gap','top','right','bottom','left','z-index','overflow','box-sizing'],Flex:['flex-direction','flex-wrap','justify-content','align-items','align-self','flex','order'],Grid:['grid-template-columns','grid-template-rows','grid-column','grid-row','place-items'],Motion:['transform','transform-origin','transition','filter','cursor','object-fit','object-position']};

function Draft({label,value,onApply,multiline=false}:{label:string;value:string;onApply:(v:string)=>void;multiline?:boolean}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <label>{label}{multiline?<textarea value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onApply(draft);}}/>:<input list={label==='font-family'?'webbit-font-families':undefined} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value)onApply(draft);}} onKeyDown={e=>{if(e.key==='Enter'){e.currentTarget.blur();}}}/>}</label>;}

export function ElementRibbon({source,id,onChange,onSelect,onError,assetPaths=[],page='index.html',fontFamilies=[],onImportFont}:{fontFamilies?:string[];onImportFont?:()=>void;assetPaths?:string[];page?:string;source:string;id:number;onChange:(s:string)=>void;onSelect:(id:number|null)=>void;onError:(message:string)=>void}){

 const [section,setSection]=useState('Appearance'),[state,setState]=useState<ElementState>('normal'),[newAttr,setNewAttr]=useState(''),[newValue,setNewValue]=useState(''),[cssName,setCssName]=useState(''),[cssValue,setCssValue]=useState('');

 const node=sourceElement(source,id);useEffect(()=>{setSection(node?.tagName==='table'?'Table':node?.tagName==='img'?'Image':node&&(['nav','ul','ol','menu'].includes(node.tagName)||node.attrs.some(a=>a.name==='data-wb-block'&&/menu|navigation/i.test(a.value)))?'Menu':'Appearance');setState('normal');},[id,node?.tagName]);if(!node)return <p>Select an element.</p>;const isMenu=['nav','ul','ol','menu'].includes(node.tagName)||node.attrs.some(a=>a.name==='data-wb-block'&&/menu|navigation/i.test(a.value));const attr=(name:string)=>node.attrs.find(a=>a.name.toLowerCase()===name.toLowerCase())?.value??'';

 const safe=(fn:()=>string,structural=false)=>{try{onChange(fn());if(structural)onSelect(null);}catch(e){onError(String(e));}};

 const set=(name:string,value:string)=>safe(()=>value===''?removeElementAttribute(source,id,name):setElementAttribute(source,id,name,value));

 const inline=document.createElement('div').style;inline.cssText=attr('style');let values:Record<string,string>={},configError='';try{values=elementRules(source,id,state);}catch(e){configError=String(e);}

 const value=(name:string)=>values[name]??(state==='normal'?inline.getPropertyValue(name):'');

 const style=(name:string,v:string)=>safe(()=>state==='normal'?updateStyle(updateElementRules(source,id,state,{[name]:''}),id,{[name]:v}):updateElementRules(source,id,state,{[name]:v}));

 const loc=node.sourceCodeLocation;const markup=loc?source.slice(loc.startOffset,loc.endOffset):'';const textOnly=node.childNodes.every(n=>n.nodeName==='#text');const inner=node.childNodes.map(n=>'value'in n?n.value:'').join('');

 const plainText=(v:string)=>{if(!loc?.startTag||!loc.endTag)throw new Error('This element has no text content.');const encoded=v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');return source.slice(0,loc.startTag.endOffset)+encoded+source.slice(loc.endTag.startOffset);};

 return <div className="element-ribbon"><datalist id="webbit-font-families">{['system-ui','Arial','Georgia','Times New Roman','Courier New',...new Set(fontFamilies)].map(f=><option key={f} value={f}/>)}</datalist>{configError&&<p role="alert">{configError}</p>}<div className="element-toolbar"><label>Element<select aria-label="Selected page element" value={id} onChange={e=>onSelect(Number(e.target.value))}>{sourceNodes(source).map((n,i)=>n.sourceCodeLocation?.startTag?<option key={i} value={i}>{n.tagName}{n.attrs.find(a=>a.name==='id')?.value?' #'+n.attrs.find(a=>a.name==='id')!.value:''} · {i}</option>:null)}</select></label><nav aria-label="Element control sections">{[...(isMenu?['Menu']:[]),...(node.tagName==='table'?['Table']:[]),...(node.tagName==='img'?['Image']:[]),'Background','Appearance','Content','Behavior','Effects','Layers','Attributes','Code'].map(name=><button key={name} aria-pressed={section===name} onClick={()=>setSection(name)}>{name}</button>)}</nav><button onClick={()=>safe(()=>moveElement(source,id,'up'),true)}>Move up</button><button onClick={()=>safe(()=>moveElement(source,id,'down'),true)}>Move down</button><button onClick={()=>safe(()=>removeElement(source,id),true)}>Delete element</button></div>

 {(section==='Appearance'||section==='Effects')&&<><div className="element-state"><label>Editing state<select value={state} onChange={e=>setState(e.target.value as ElementState)}>{elementStates.map(s=><option key={s} value={s}>{({normal:'Normal',hover:'Hover',focus:'Keyboard focus',active:'Pressed',disabled:'Disabled'})[s]}</option>)}</select></label><span>Blank inherits the page stylesheet. Use CSS units: px, %, rem, auto.</span></div>{section==='Appearance'?<div className="style-sections">{Object.entries(styleGroups).map(([group,names])=><details key={group} open={group==='Typography'}><summary>{group}</summary>{group==='Typography'&&<><button onClick={onImportFont}>Import fonts…</button><label>Font family<select aria-label="Font family" value={value('font-family').replaceAll('"','')} onChange={e=>style('font-family',e.target.value)}><option value="">Inherit stylesheet</option>{['system-ui','Arial','Georgia','Times New Roman','Courier New',...new Set(fontFamilies)].map(f=><option key={f} value={f}>{f}</option>)}</select></label></>}<div className="element-fields">{names.map(name=><Draft key={name} label={name} value={value(name)} onApply={v=>style(name,v)}/>)}</div></details>)}</div>:<><div className="effect-presets">{elementPresets.map(p=><button key={p.name} onClick={()=>{if(state==='normal')setState('hover');safe(()=>{let s=updateElementRules(source,id,'normal',{transition:'transform .2s ease, box-shadow .2s ease, background-color .2s ease, color .2s ease, filter .2s ease'});return updateElementRules(s,id,state==='normal'?'hover':state,p.values as Record<string,string>);});}}>{p.name}</button>)}</div><p>Presets apply to Hover unless another state is selected. Customize colors, movement, shadows and timing below. Reduced motion disables transforms and transitions.</p><div className="element-fields">{['background-color','color','background-image','box-shadow','transform','outline','outline-offset','opacity','filter','transition'].map(name=><Draft key={name} label={name} value={value(name)} onApply={v=>style(name,v)}/>)}</div><button onClick={()=>safe(()=>updateElementRules(source,id,state,Object.fromEntries(Object.keys(values).map(k=>[k,'']))))}>Clear stylesheet effects for this state</button></>}<div className="custom-property"><input aria-label="CSS property name" placeholder="Any CSS property" value={cssName} onChange={e=>setCssName(e.target.value)}/><input aria-label="CSS property value" placeholder="Value" value={cssValue} onChange={e=>setCssValue(e.target.value)}/><button onClick={()=>style(cssName,cssValue)}>Apply property</button></div></>}

 {section==='Table'&&<TableRibbon source={source} id={id} onChange={onChange} onSelect={onSelect} onError={onError}/>}

 {section==='Image'&&<><p>Choose a project image or enter a source path under Content. Alt text describes the image to visitors using assistive technology.</p><label>Project image<select defaultValue="" onChange={e=>{if(e.target.value)set('src','../'.repeat(page.split('/').length-1)+e.target.value.split('/').map(encodeURIComponent).join('/'));}}><option value="">Choose an imported image…</option>{assetPaths.map(p=><option key={p}>{p}</option>)}</select></label><div className="element-fields">{['src','alt','width','height','loading'].map(name=><Draft key={name} label={name} value={attr(name)} onApply={v=>set(name,v)}/>)}{['width','height','object-fit','object-position','aspect-ratio','border-radius','filter','opacity'].map(name=><Draft key={'css-'+name} label={'CSS '+name} value={inline.getPropertyValue(name)} onApply={v=>safe(()=>updateStyle(source,id,{[name]:v}))}/>)}</div></>}

 {section==='Background'&&<><p>Background applies to the selected element. Choose Page in the element selector to change the whole page.</p><label>Project background image<select defaultValue="" onChange={e=>{if(e.target.value)style('background-image','url("'+'../'.repeat(page.split('/').length-1)+e.target.value.split('/').map(encodeURIComponent).join('/')+'")');}}><option value="">Choose an imported image…</option>{assetPaths.map(p=><option key={p}>{p}</option>)}</select></label><div className="element-fields">{['background-color','background-image','background-size','background-position','background-repeat','background-attachment','background-blend-mode'].map(name=><Draft key={name} label={name} value={value(name)} onApply={v=>style(name,v)}/>)}</div><div className="effect-presets"><button onClick={()=>style('background-image','linear-gradient(135deg,#382662,#79b8af)')}>Gradient background</button><button onClick={()=>style('background-size','cover')}>Cover area</button><button onClick={()=>style('background-size','contain')}>Contain image</button><button onClick={()=>style('background-repeat','repeat')}>Tile image</button></div></>}

 {section==='Menu'&&<MenuRibbon source={source} id={id} onChange={onChange} onSelect={onSelect} onError={onError}/>}

 {section==='Layers'&&<><p>Overlapping elements use real CSS position and z-index. Stacking is relative to ancestor stacking contexts; a child cannot escape an ancestor context. Transparent areas do not change pointer hit testing.</p><div className="effect-presets"><button onClick={()=>safe(()=>updateStyle(source,id,{position:inline.position||'relative','z-index':String(Math.max(0,...sourceNodes(source).map(n=>{const style=document.createElement('div').style;style.cssText=n.attrs.find(a=>a.name==='style')?.value??'';return Number(style.zIndex)||0;}))+1)}))}>Bring to front</button><button onClick={()=>safe(()=>updateStyle(source,id,{position:inline.position||'relative','z-index':String((Number(inline.zIndex)||0)+1)}))}>One layer forward</button><button onClick={()=>safe(()=>updateStyle(source,id,{position:inline.position||'relative','z-index':String((Number(inline.zIndex)||0)-1)}))}>One layer backward</button><button onClick={()=>safe(()=>updateStyle(source,id,{position:'absolute',top:'0',left:'0','z-index':'1'}))}>Overlay at positioning origin</button><button onClick={()=>safe(()=>updateStyle(source,id,{position:'',top:'',left:'',right:'',bottom:'','z-index':''}))}>Return to normal flow</button></div><div className="element-fields">{['position','z-index','top','left','right','bottom','width','height','opacity','pointer-events','isolation'].map(name=><Draft key={name} label={name} value={inline.getPropertyValue(name)} onApply={v=>safe(()=>updateStyle(source,id,{[name]:v}))}/>)}</div><label>Pick a covered element<select value={id} onChange={e=>onSelect(Number(e.target.value))}>{sourceNodes(source).map((n,i)=>n.sourceCodeLocation?.startTag?<option key={i} value={i}>{n.tagName} {n.attrs.find(a=>a.name==='id')?.value??''} · {i}</option>:null)}</select></label></>}

 {section==='Content'&&<div className="element-fields">{textOnly&&loc?.endTag&&!['script','style'].includes(node.tagName)&&<Draft label="Text / label" value={inner} onApply={v=>safe(()=>plainText(v))}/>}<Draft label="ID" value={attr('id')} onApply={v=>set('id',v)}/><Draft label="Classes" value={attr('class')} onApply={v=>set('class',v)}/><Draft label="Tooltip" value={attr('title')} onApply={v=>set('title',v)}/>{(typeAttrs[node.tagName]??[]).map(name=><Draft key={name} label={name} value={attr(name)} onApply={v=>set(name,v)}/>)}{!textOnly&&<p>This element contains other elements. Select a child above to edit it, or use Code to change its markup.</p>}</div>}

 {section==='Behavior'&&<><div className="element-fields">{(typeAttrs[node.tagName]??['role','tabindex']).map(name=><Draft key={name} label={name} value={attr(name)} onApply={v=>set(name,v)}/>)}{['role','tabindex','aria-label','aria-controls','aria-expanded'].filter(n=>!(typeAttrs[node.tagName]??[]).includes(n)).map(name=><Draft key={name} label={name} value={attr(name)} onApply={v=>set(name,v)}/>)}</div><div className="element-booleans">{['hidden',...(boolAttrs[node.tagName]??[])].map(name=><label key={name}><input type="checkbox" checked={node.attrs.some(a=>a.name===name)} onChange={e=>safe(()=>e.target.checked?setElementAttribute(source,id,name,''):removeElementAttribute(source,id,name))}/>{name}</label>)}</div><p>Button type supports button, submit or reset. Links use href; forms use action and method. Custom events and integration code can be edited under Code. Scripts run in browser preview/export, not inside the editor.</p></>}

 {section==='Attributes'&&<><div className="element-fields">{node.attrs.filter(a=>!a.name.startsWith('on')&&a.name!=='srcdoc').map(a=><div key={a.name}><Draft label={a.name} value={a.value} onApply={v=>set(a.name,v)}/><button aria-label={`Remove ${a.name} attribute`} onClick={()=>safe(()=>removeElementAttribute(source,id,a.name))}>Remove</button></div>)}</div><div className="custom-property"><input aria-label="New attribute name" placeholder="Attribute name, data-* or aria-*" value={newAttr} onChange={e=>setNewAttr(e.target.value)}/><input aria-label="New attribute value" placeholder="Value" value={newValue} onChange={e=>setNewValue(e.target.value)}/><button onClick={()=>safe(()=>setElementAttribute(source,id,newAttr,newValue))}>Add attribute</button></div></>}

 {section==='Code'&&<><p>Complete HTML for this element, including custom attributes, nested elements and event handlers. Applying structural changes clears the selection. Preview keeps scripts isolated; test custom behavior with Preview in Browser.</p><MarkupEditor key={id} value={markup} apply={v=>safe(()=>replaceElementMarkup(source,id,v),true)}/></>}

 </div>;

}

function MarkupEditor({value,apply}:{value:string;apply:(s:string)=>void}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <><textarea className="element-markup" aria-label="Element HTML" value={draft} onChange={e=>setDraft(e.target.value)}/><button onClick={()=>apply(draft)}>Apply element HTML</button></>;}

