import {projectFromFiles,validateFiles,type SiteProject} from './project';
export type StorageMode='sensitive'|'full';
export function storageMode(project:SiteProject):StorageMode {try{return JSON.parse(project.files['webbit.security.json']??'{}').storage==='full'?'full':'sensitive';}catch{return 'full';}}
const encoder=new TextEncoder(),aad=encoder.encode('Webbit encrypted package v1');
const MAX=300_000_000;
function b64(bytes:Uint8Array):string {let result='';for(let i=0;i<bytes.length;i+=32768)result+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(result);}
function bytes(text:unknown):Uint8Array<ArrayBuffer>{if(typeof text!=='string'||text.length>MAX*1.4||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw new Error('Invalid encrypted package.');return Uint8Array.from(atob(text),c=>c.charCodeAt(0));}
async function key(password:string,salt:Uint8Array<ArrayBuffer>){const input=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},input,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export type VaultPayload={kind:'project'|'deployment';files:Record<string,string>;assets:Record<string,string>};
function validatePayload(payload:VaultPayload){if(!['project','deployment'].includes(payload.kind))throw new Error('Invalid package kind');validateFiles(payload.files);validateFiles(payload.assets);const paths=Object.keys(payload.files).concat(Object.keys(payload.assets));const seen=new Set(paths.map(p=>p.toLowerCase()));if(seen.size!==paths.length)throw new Error('Duplicate package path');for(const p of paths){const parts=p.toLowerCase().split('/');parts.pop();while(parts.length){if(seen.has(parts.join('/')))throw new Error('File/folder collision');parts.pop();}}for(const asset of Object.values(payload.assets))if(!/^data:[^;,]+;base64,[A-Za-z0-9+/]*={0,2}$/.test(asset))throw new Error('Invalid asset');}
export async function sealPackage(payload:VaultPayload,password:string):Promise<string>{validatePayload(payload);if(password.length<12||password.length>1024)throw new Error('Use a passphrase between 12 and 1,024 characters.');const plain=encoder.encode(JSON.stringify(payload));if(plain.length>MAX)throw new Error('Encrypted package limit: 300 MB.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));try{const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},await key(password,salt),plain);return JSON.stringify({format:'webbit-encrypted',version:1,kdf:'PBKDF2-SHA256',iterations:600000,cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),data:b64(new Uint8Array(ciphertext))});}finally{plain.fill(0);}}
export async function openPackage(raw:string,password:string):Promise<VaultPayload>{if(raw.length>MAX*1.4)throw new Error('Encrypted package is too large.');let plain:Uint8Array|undefined;try{const e=JSON.parse(raw);if(e.format!=='webbit-encrypted'||e.version!==1||e.kdf!=='PBKDF2-SHA256'||e.iterations!==600000||e.cipher!=='AES-256-GCM')throw new Error();const salt=bytes(e.salt),iv=bytes(e.iv),data=bytes(e.data);if(salt.length!==16||iv.length!==12||data.length<16)throw new Error();plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:aad},await key(password,salt),data));const payload=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(plain));validatePayload(payload);projectFromFiles(payload.files,payload.assets);return payload;}catch{throw new Error('Cannot unlock package: wrong passphrase, damaged data or unsupported format.');}finally{plain?.fill(0);}}
