import type {SiteProject} from './project';
import auth from '../manager-runtime/src/AuthStore.php?raw';
import session from '../manager-runtime/src/Session.php?raw';
import totp from '../manager-runtime/src/Totp.php?raw';
import members from '../manager-runtime/src/Members.php?raw';
import setup from '../manager-runtime/members-setup.php?raw';
export type AccessConfig={enabled:boolean;title:string;pages:string[]};
export function accessConfig(project:SiteProject):AccessConfig {try{const v=JSON.parse(project.files['webbit.access.json']??'{}');return {enabled:v.enabled===true,title:typeof v.title==='string'?v.title.slice(0,100):'Member access',pages:Array.isArray(v.pages)?v.pages.filter((p:unknown)=>typeof p==='string'&&/\.html?$/i.test(p)&&project.files[p]!==undefined):[]};}catch{return {enabled:false,title:'Member access',pages:[]};}}
export function addMemberExport(files:Record<string,string>,project:SiteProject){const config=accessConfig(project);if(!config.enabled)return files;const out={...files};if(Object.keys(project.files).some(p=>/^members\//i.test(p)))throw new Error('The members/ route is reserved. Rename that project folder first.');const pages:Record<string,{url:string;label:string}>={};
 config.pages.forEach((page,i)=>{const id='page-'+i;const php=page.replace(/\.html?$/i,'.php');if(project.files[php]!==undefined)throw new Error(`Protected-page route already exists: ${php}`);pages[id]={url:'/'+php.split('/').map(encodeURIComponent).join('/'),label:page};out[`private/members/pages/${id}.html`]=project.files[page];out[`public/${page}`]=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${encodeURIComponent(php.split('/').pop()!)}"><title>Member page</title></head><body><a href="${php.split('/').pop()}">Open member page</a></body></html>`;const levels=page.split('/').length;out[`public/${php}`]=`<?php\ndeclare(strict_types=1);\nrequire_once dirname(__DIR__,${levels}) . '/private/member-runtime/Members.php';\nWebbit\\Manager\\Members::page(dirname(__DIR__,${levels}) . '/private/members', dirname(__DIR__,${levels-1||1})${levels===1?" . '/public'":''}, '${id}');\n`;});
 for(const [name,text] of Object.entries({'AuthStore.php':auth,'Session.php':session,'Totp.php':totp,'Members.php':members}))out['private/member-runtime/'+name]=text.replace(/^\uFEFF/,'');
 out['public/members/index.php']="<?php\ndeclare(strict_types=1);\nrequire_once dirname(__DIR__,2).'/private/member-runtime/Members.php';\nWebbit\\Manager\\Members::run(dirname(__DIR__,2).'/private/members',dirname(__DIR__));\n";
 out['public/members/style.css']=':root{font:17px/1.6 system-ui;color:#243142;background:#eef2f7}main{max-width:620px;margin:6vh auto;background:white;padding:36px;border-radius:14px}label{display:grid;gap:6px;margin:16px 0}input,button{font:inherit;padding:10px;border:1px solid #abb5c6;border-radius:6px}button{background:#594293;color:white}code,pre{overflow-wrap:anywhere;white-space:pre-wrap}a{color:#594293}';
 out['private/members/config.json']=JSON.stringify({title:config.title,pages},null,2);out['members-setup.php']=setup.replace(/^\uFEFF/,'');out['README-MEMBERS.md']='# Member access\n\nSet your HTTPS server document root to public/. Keep private/ outside it, with owner-only access (0700 on Unix; restricted ACL on Windows). PHP 8.2+, sodium and pdo_sqlite are required. Set private/members and its child directories to 0700. Run php members-setup.php USERNAME to create a one-use 24-hour invitation; give it privately to the member. The member chooses a password and enrolls TOTP, then saves one-use recovery codes. Run php members-setup.php USERNAME disable to revoke access.\n\nMember accounts and cookies are separate from administrator accounts; members cannot edit the site. All members can access the selected pages. Protected HTML is stored privately, served only through the generated PHP gate. Authenticator secrets use authenticated libsodium encryption with an automatically generated 256-bit key per account. Passwords and recovery codes are hashed. HTTPS protects transport; it is mandatory. Back up private account databases together with their key.bin files in encrypted backup storage. Encryption does not protect against an attacker who obtains both the key and database. Page HTML and shared assets are not encrypted at rest.\n\nShared images, styles and scripts remain public: do not place confidential files there.\n\nProtected pages are excluded from the generated admin field editor; edit their source in Webbit and redeploy. Keep private account databases, keys and sessions when deploying updates; generated exports never include existing accounts. Invitations are created via CLI, not public signup. Self-service password resets, member groups and a member management UI are not implemented yet. This Beta requires deployment testing and independent security review.\n';return out;}
