import {sourceNodes,escapeHtml,insertMarkup} from './blocks';
import {sourceElement} from './preview';
import {setElementAttribute} from './inspector';
export function menuItems(source:string,id:number){const nodes=sourceNodes(source),root=nodes[id],loc=root?.sourceCodeLocation;if(!root||!loc)return [];const within=nodes.map((node,index)=>({node,index})).filter(({node})=>node.sourceCodeLocation&&node.sourceCodeLocation.startOffset>loc.startOffset&&node.sourceCodeLocation.endOffset<=loc.endOffset);const cards=within.filter(({node})=>node.attrs.some(a=>a.name==='data-wb-row'));const lists=within.filter(({node})=>node.tagName==='li');const chosen=cards.length?cards:lists.length?lists:within.filter(({node})=>node.tagName==='a');return chosen.map(({node,index})=>{let depth=0,parent=node.parentNode;while(parent&&parent!==root){if('tagName'in parent&&parent.tagName==='li')depth++;parent='parentNode'in parent?parent.parentNode:null;}const region=node.sourceCodeLocation!;const contents=nodes.map((node,i)=>({node,i})).filter(({node})=>node.sourceCodeLocation&&node.sourceCodeLocation.startOffset>=region.startOffset&&node.sourceCodeLocation.endOffset<=region.endOffset);const link=contents.find(n=>n.node.tagName==='a');const label=contents.find(n=>['a','h3','h2'].includes(n.node.tagName)&&n.node.childNodes.some(c=>c.nodeName==='#text'));const paragraphs=contents.filter(n=>n.node.tagName==='p');const picture=contents.find(n=>n.node.tagName==='img');return {descriptionId:paragraphs[0]?.i,description:paragraphs[0]?.node.childNodes.map(c=>'value'in c?c.value:'').join('')??'',priceId:paragraphs[1]?.i,price:paragraphs[1]?.node.childNodes.map(c=>'value'in c?c.value:'').join('')??'',imageId:picture?.i,image:picture?.node.attrs.find(a=>a.name==='src')?.value??'',id:index,depth,tag:node.tagName,label:label?.node.childNodes.map(c=>'value'in c?c.value:'').join('').trim()||node.tagName,linkId:link?.i,href:link?.node.attrs.find(a=>a.name==='href')?.value??'',labelId:label?.i};});}
export function menuContainer(source:string,id:number){const nodes=sourceNodes(source),root=nodes[id];if(!root)return id;const children=root.childNodes.filter(n=>'tagName'in n);const target=children.find(n=>'tagName'in n&&['ul','ol','menu'].includes(n.tagName))??children.find(n=>'tagName'in n&&n.attrs.some(a=>a.name==='class'&&a.value.includes('wb-data-cards')));return target?nodes.indexOf(target as ReturnType<typeof sourceNodes>[number]):id;}
export function addMenuItem(source:string,id:number,label:string,href:string,image:string,description:string,price:string){const container=menuContainer(source,id);const parent=sourceElement(source,container)!;let link='<a>Link</a>';link=setElementAttribute(link,sourceNodes(link).findIndex(n=>n.tagName==='a'),'href',href||'#');const open=link.match(/<a[^>]*>/)![0];let picture='';if(image){let img='<img alt="">';img=setElementAttribute(img,sourceNodes(img).findIndex(n=>n.tagName==='img'),'src',image);picture=img;}const cards=parent.attrs.some(a=>a.name==='class'&&a.value.includes('wb-data-cards'));const markup=cards?`<article data-wb-row>${picture}<h3>${escapeHtml(label)}</h3><p>${escapeHtml(description)}</p><p>${escapeHtml(price)}</p></article>`:`${['ul','ol','menu'].includes(parent.tagName)?'<li>':''}${open}${picture}${escapeHtml(label)}</a>${['ul','ol','menu'].includes(parent.tagName)?'</li>':''}`;return insertMarkup(source,markup,container);}
function transfer(source:string,id:number,at:number,wrapStart='',wrapEnd=''){const loc=sourceElement(source,id)?.sourceCodeLocation;if(!loc)throw new Error('Select a menu item.');if(at>=loc.startOffset&&at<=loc.endOffset)throw new Error('Cannot nest an item inside itself.');const copy=source.slice(loc.startOffset,loc.endOffset),length=loc.endOffset-loc.startOffset;const without=source.slice(0,loc.startOffset)+source.slice(loc.endOffset);const offset=at>loc.endOffset?at-length:at;return without.slice(0,offset)+wrapStart+copy+wrapEnd+without.slice(offset);}
export function nestMenuItem(source:string,id:number){const node=sourceElement(source,id);if(node?.tagName!=='li'||!node.parentNode||!('childNodes'in node.parentNode))throw new Error('Nesting uses list-based menu items (li).');const siblings=node.parentNode.childNodes.filter(n=>'tagName'in n&&n.tagName==='li');const previous=siblings[siblings.indexOf(node)-1];if(!previous||!('childNodes'in previous))throw new Error('Move this item after another item before nesting.');const list=previous.childNodes.find(n=>'tagName'in n&&['ul','ol'].includes(n.tagName));const target=list??previous;const at='tagName'in target?target.sourceCodeLocation?.endTag?.startOffset:undefined;if(at===undefined)throw new Error('Missing closing menu tag.');return transfer(source,id,at,list?'':'<ul>',list?'':'</ul>');}
export function unnestMenuItem(source:string,id:number){const node=sourceElement(source,id),list=node?.parentNode;const parent=list&&'parentNode'in list?list.parentNode:null;if(node?.tagName!=='li'||!parent||!('tagName'in parent)||parent.tagName!=='li'||!parent.sourceCodeLocation)throw new Error('This item is already at the top level.');return transfer(source,id,parent.sourceCodeLocation.endOffset);}

export function menuCategories(source:string,id:number){const root=sourceElement(source,id)?.sourceCodeLocation;return sourceNodes(source).flatMap((node,index)=>{const label=node.attrs.find(a=>a.name==='data-wb-menu-category')?.value,loc=node.sourceCodeLocation;return label!==undefined&&root&&loc&&loc.startOffset>root.startOffset&&loc.endOffset<root.endOffset?[{id:index,label}]:[];});}
export function addMenuCategory(source:string,id:number,label:string){const parent=sourceElement(source,menuContainer(source,id));if(!parent?.attrs.some(a=>a.name==='class'&&a.value.split(/\s+/).includes('wb-data-cards')))throw new Error('Categories require a restaurant menu. Use Nest for navigation lists.');return insertMarkup(source,`<section data-wb-menu-category="${escapeHtml(label)}"><h3>${escapeHtml(label)}</h3><div class="wb-data-cards"></div></section>`,menuContainer(source,id));}
export function moveMenuItemTo(source:string,id:number,targetId:number){const container=menuContainer(source,targetId),at=sourceElement(source,container)?.sourceCodeLocation?.endTag?.startOffset;if(at===undefined)throw new Error('Select a destination category.');return transfer(source,id,at);}
export function setMenuImage(source:string,id:number,path:string){let image='<img alt="">';image=setElementAttribute(image,sourceNodes(image).findIndex(n=>n.tagName==='img'),'src',path);const at=sourceElement(source,id)?.sourceCodeLocation?.startTag?.endOffset;if(at===undefined)throw new Error('Select an item.');return source.slice(0,at)+image+source.slice(at);}
