import React,{useEffect,useRef,useState} from 'react';
export type RibbonCommand={label:string;hint:string;run:()=>void;disabled?:boolean};
type Floating={x:number;y:number};
export function Ribbon({visible,onToggle,groups,disabled,context}:{visible:boolean;onToggle:()=>void;groups:Record<string,RibbonCommand[]>;disabled:boolean;context?:{key:string;label:string;content:React.ReactNode}}){
 const [tab,setTab]=useState(groups.Home?'Home':Object.keys(groups)[0]);const [floating,setFloating]=useState<Record<string,Floating>>({});const root=useRef<HTMLElement>(null);const drag=useRef<{name:string;x:number;y:number;left:number;top:number;floating:boolean}|null>(null);const [dragging,setDragging]=useState(false);
 const contextName='Element';const names=[...Object.keys(groups),...(context?[contextName]:[])];const title=(name:string)=>name===contextName?context?.label??'Element':name;
 useEffect(()=>{if(context)setTab(contextName);else setTab(current=>current===contextName?'Home':current);},[context?.key]);
 const clamp=(x:number,y:number)=>({x:Math.max(0,Math.min(x,window.innerWidth-260)),y:Math.max(0,Math.min(y,window.innerHeight-60))});
 const dock=(name:string)=>{setFloating(current=>{const next={...current};delete next[name];return next;});setTab(name);};
 const start=(event:React.PointerEvent,name:string,isFloating:boolean)=>{if(event.button!==0||disabled||(event.target as HTMLElement).closest('input,select,textarea,.dock-panel'))return;const pos=floating[name]??{x:event.clientX-90,y:event.clientY-15};drag.current={name,x:event.clientX,y:event.clientY,left:pos.x,top:pos.y,floating:isFloating};event.currentTarget.setPointerCapture(event.pointerId);};
 const move=(event:React.PointerEvent)=>{const d=drag.current;if(!d)return;const dx=event.clientX-d.x,dy=event.clientY-d.y;if(Math.hypot(dx,dy)<7&&!dragging)return;setDragging(true);if(d.floating)setFloating(old=>({...old,[d.name]:clamp(d.left+dx,d.top+dy)}));};
 const end=(event:React.PointerEvent)=>{const d=drag.current;drag.current=null;if(!d)return;const moved=Math.hypot(event.clientX-d.x,event.clientY-d.y)>7;const bounds=root.current?.getBoundingClientRect();const over=!!bounds&&event.clientX>=bounds.left&&event.clientX<=bounds.right&&event.clientY>=bounds.top&&event.clientY<=bounds.bottom;if(moved){if(over)dock(d.name);else setFloating(old=>({...old,[d.name]:clamp(d.floating?d.left+event.clientX-d.x:event.clientX-90,d.floating?d.top+event.clientY-d.y:event.clientY-16)}));}setDragging(false);};
 const content=(name:string)=>name===contextName?context?.content:<div className="ribbon-commands">{groups[name]?.map(command=><button key={command.label} disabled={disabled||command.disabled} onClick={command.run}><strong>{command.label}</strong><small>{command.hint}</small></button>)}</div>;
 if(!visible)return <div className="ribbon-collapsed"><button aria-expanded="false" onClick={onToggle}>Show ribbon ▾</button></div>;
 const active=names.includes(tab)?tab:names[0];
 return <><section ref={root} className={`ribbon ${dragging?'ribbon-dragging':''}`} aria-label="Command ribbon"><div className="ribbon-tabs" role="tablist" aria-label="Ribbon categories">{names.map((name,i)=><button key={name} role="tab" id={`ribbon-${name}`} aria-controls="ribbon-content" aria-selected={active===name} tabIndex={active===name?0:-1} title="Drag this tab out to float its panel" onClick={()=>setTab(name)} onPointerDown={e=>start(e,name,false)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setDragging(false);}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?names.length-1:(i+(e.key==='ArrowRight'?1:-1)+names.length)%names.length;setTab(names[next]);document.getElementById(`ribbon-${names[next]}`)?.focus();}}}>{title(name)}{floating[name]?' ↗':''}</button>)}<button className="ribbon-hide" onClick={onToggle} aria-expanded="true" title="Hide ribbon (Ctrl+F1)">Hide ribbon ▴</button></div><div id="ribbon-content" role="tabpanel" aria-labelledby={`ribbon-${active}`} className="ribbon-content">{floating[active]?<div className="floating-notice">{title(active)} is in a floating panel. Drag its header here to dock it.<button onClick={()=>dock(active)}>Dock {title(active)}</button></div>:<><button className="undock-panel" disabled={disabled} onClick={()=>setFloating(old=>({...old,[active]:clamp(320,220)}))}>Float {title(active)} ↗</button><fieldset disabled={disabled} className="ribbon-fieldset">{content(active)}</fieldset></>}</div></section>{names.filter(name=>floating[name]).map(name=><section key={name} className={`ribbon-floating ${active===name?'active':''}`} style={{left:floating[name].x,top:floating[name].y}} role="region" aria-label={`${title(name)} floating panel`}><header onPointerDown={e=>start(e,name,true)} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{drag.current=null;setDragging(false);}}><strong>{title(name)}</strong><span>Drag to move or dock</span><button className="dock-panel" onClick={()=>dock(name)}>Dock</button></header><fieldset disabled={disabled} className="ribbon-fieldset">{content(name)}</fieldset></section>)}</>;
}
