import React from 'react';
import {sourceElement} from './preview';
import {sourceNodes} from './blocks';
import {setElementAttribute} from './inspector';
export function updateStyle(source:string,id:number,values:Record<string,string>):string{const node=sourceElement(source,id);if(!node)throw new Error('Select an element.');const style=document.createElement('div').style;style.cssText=node.attrs.find(a=>a.name==='style')?.value??'';for(const [name,value] of Object.entries(values)){if(value)style.setProperty(name,value);else style.removeProperty(name);}return setElementAttribute(source,id,'style',style.cssText);}
export function StyleControls({source,selected,onChange,onError}:{source:string;selected:number|null;onChange:(source:string)=>void;onError:(message:string)=>void}){
 const node=selected===null?null:sourceElement(source,selected);const style=document.createElement('div').style;style.cssText=node?.attrs.find(a=>a.name==='style')?.value??'';
 const set=(values:Record<string,string>,id=selected)=>{if(id===null)return;try{onChange(updateStyle(source,id,values));}catch(e){onError(String(e));}};
 const body=sourceNodes(source).findIndex(n=>n.tagName==='body');
 return <section className="style-ribbon" aria-label="Element formatting"><div className="style-group"><strong>{node?`Selected: ${node.tagName}`:'Select an element to format'}</strong><label>Font<select disabled={!node} value={style.fontFamily} onChange={e=>set({'font-family':e.target.value})}><option value="">Inherited</option>{['Arial','Verdana','Georgia','Tahoma','Times New Roman','Consolas','system-ui'].map(f=><option key={f} value={f}>{f}</option>)}</select></label><label>Size (px)<input type="number" min={6} max={300} disabled={!node} value={parseFloat(style.fontSize)||''} onChange={e=>set({'font-size':e.target.value?`${e.target.value}px`:''})}/></label><button disabled={!node} aria-pressed={style.fontWeight==='700'} onClick={()=>set({'font-weight':style.fontWeight==='700'?'':'700'})}><b>Bold</b></button><button disabled={!node} aria-pressed={style.fontStyle==='italic'} onClick={()=>set({'font-style':style.fontStyle==='italic'?'':'italic'})}><i>Italic</i></button><label>Text color<input type="color" disabled={!node} onChange={e=>set({color:e.target.value})}/></label><label>Align<select disabled={!node} value={style.textAlign} onChange={e=>set({'text-align':e.target.value})}><option value="">Inherited</option>{['left','center','right','justify'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 <div className="style-group"><label>Fill<input type="color" disabled={!node} onChange={e=>set({'background-color':e.target.value})}/></label><label>Border (px)<input type="number" min={0} max={40} disabled={!node} value={parseFloat(style.borderWidth)||''} onChange={e=>set({'border-width':e.target.value?`${e.target.value}px`:'','border-style':e.target.value?'solid':''})}/></label><label>Border color<input type="color" disabled={!node} onChange={e=>set({'border-color':e.target.value})}/></label><label>Round (px)<input type="number" min={0} max={200} disabled={!node} value={parseFloat(style.borderRadius)||''} onChange={e=>set({'border-radius':e.target.value?`${e.target.value}px`:''})}/></label><label>Padding (px)<input type="number" min={0} max={300} disabled={!node} value={parseFloat(style.padding)||''} onChange={e=>set({padding:e.target.value?`${e.target.value}px`:''})}/></label><label>Page background<input type="color" disabled={body<0} onChange={e=>set({'background-color':e.target.value},body)}/></label><button disabled={body<0} onClick={()=>set({'background-color':'','background-image':''},body)}>Clear page background</button></div></section>;
}
