import React,{useState} from 'react';
import {extraTemplates} from './templates';
const categories:Record<string,string>={restaurant:'Restaurants',business:'Technology',product:'Technology',services:'Services',realestate:'Property',catalog:'Shopping',photography:'Creative',agency:'Creative',portfolio:'Creative',event:'Community',nonprofit:'Community',resume:'Personal',education:'Education',magazine:'Publishing',blog:'Publishing',blank:'Blank'};
const templates=[{id:'blank',name:'Blank Site',bg:'#fff',color:'#555'},{id:'business',name:'Business & computer care',bg:'#e9e5dc',color:'#34453f'},{id:'portfolio',name:'Portfolio',bg:'#e1dcf1',color:'#533f80'},{id:'blog',name:'Blog & stories',bg:'#e8cdbc',color:'#81472b'},...extraTemplates];
export function TemplateGallery({onChoose}:{onChoose:(id:string)=>void}){
 const [category,setCategory]=useState(''),[search,setSearch]=useState('');
 const visible=templates.filter(t=>(!category||category==='All'||categories[t.id]===category)&&(!search.trim()||`${t.name} ${categories[t.id]}`.toLowerCase().includes(search.trim().toLowerCase())));
 const browsing=!!category||!!search.trim();
 return <><label className="template-search">Search templates<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Restaurant, technology, portfolio…"/></label><div className="template-categories" aria-label="Template categories"><button aria-pressed={!category} onClick={()=>setCategory('')}>Categories</button><button aria-pressed={category==='All'} onClick={()=>setCategory('All')}>All templates ({templates.length})</button></div>{!browsing?<><button className="blank-template" onClick={()=>onChoose('blank')}><strong>Blank Site</strong><span>Start with an empty page →</span></button><div className="category-grid">{[...new Set(Object.values(categories))].filter(c=>c!=='Blank').sort().map(c=><button key={c} onClick={()=>setCategory(c)}><strong>{c}</strong><span>{templates.filter(t=>categories[t.id]===c).length} templates →</span></button>)}</div></>:<><h2>{category&&category!=='All'?category:'Templates'} <small>({visible.length})</small></h2><div className="template-categories">{[...new Set(Object.values(categories))].sort().map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="starter-grid">{visible.map(t=><button key={t.id} onClick={()=>onChoose(t.id)}><span className="starter-art" style={{background:t.bg,color:t.color}}>{t.id!=='blank'&&<><i/><i/><i/></>}</span><strong>{t.name}</strong><span>{t.id==='blank'?'Start with an empty page →':'Open starter →'}</span></button>)}</div>{!visible.length&&<p>No matching templates. Try another search or category.</p>}</>}</>;
}
