export const extraTemplates=[
 {id:'restaurant',name:'Restaurant & café',group:'Business',brand:'Juniper Table',headline:'Gather around something good.',intro:'Seasonal plates, warm company, and a place at the table.',color:'#8a452b',bg:'#fff6e7',layout:'menu',items:['Seasonal menu','Our kitchen','Hours & location']},
 {id:'services',name:'Local services',group:'Business',brand:'Oak & Co.',headline:'Good work. Right in your neighborhood.',intro:'Reliable local expertise, from the first conversation to the final detail.',color:'#22554a',bg:'#f1f6ef',layout:'split',items:['Repairs & maintenance','Projects & upgrades','Request an estimate']},
 {id:'product',name:'Product landing',group:'Product',brand:'Orbit',headline:'Make room for your next big idea.',intro:'Introduce your product with a focused story, clear benefits, and a useful next step.',color:'#6952c5',bg:'#f5f2ff',layout:'center',items:['Simple to start','Built to grow','Made for your team']},
 {id:'catalog',name:'Shop / product catalog',group:'Product',brand:'Objects Studio',headline:'Everyday things, thoughtfully chosen.',intro:'A curated collection of useful and beautiful objects. Contact us to order.',color:'#705a40',bg:'#faf7f1',layout:'catalog',items:['The everyday collection','Objects for home','Limited editions']},
 {id:'photography',name:'Photography gallery',group:'Creative',brand:'Still / Light',headline:'A different way of seeing.',intro:'Selected photographs, quiet moments, and stories told through light.',color:'#baa784',bg:'#17191d',layout:'gallery',items:['Places','People','Details']},
 {id:'agency',name:'Creative studio',group:'Creative',brand:'Form Practice',headline:'Ideas with a point of view.',intro:'Independent design and creative direction for ambitious people.',color:'#d75f39',bg:'#fff2e9',layout:'split',items:['Brand identities','Digital experiences','Selected collaborations']},
 {id:'event',name:'Event & conference',group:'Community',brand:'Gather 2027',headline:'Meet the people shaping what comes next.',intro:'One day of conversations, workshops, and fresh perspectives.',color:'#a43275',bg:'#fff1f8',layout:'schedule',items:['09:00 · Welcome & coffee','10:00 · Opening conversation','13:00 · Workshops & demos']},
 {id:'nonprofit',name:'Nonprofit & community',group:'Community',brand:'Common Ground',headline:'Small actions. Stronger communities.',intro:'Neighbors working together to make a lasting difference.',color:'#337542',bg:'#f1f8eb',layout:'center',items:['Our mission','Volunteer with us','Community projects']},
 {id:'resume',name:'Personal résumé',group:'Personal',brand:'Alex Morgan',headline:'Curious by nature. Practical by design.',intro:'An introduction to my work, experience, and the problems I enjoy solving.',color:'#38668a',bg:'#f0f5fa',layout:'resume',items:['Experience','Selected work','Skills & education']},
 {id:'education',name:'Course & learning',group:'Education',brand:'Field Notes Academy',headline:'Learn something you can put to work.',intro:'Approachable lessons, practical exercises, and room to explore.',color:'#846016',bg:'#fff9e8',layout:'schedule',items:['01 · Start with the foundations','02 · Put ideas into practice','03 · Build your own project']},
 {id:'magazine',name:'Editorial magazine',group:'Publishing',brand:'The Sunday Edit',headline:'Stories for a slower moment.',intro:'Ideas, places, and people worth spending time with.',color:'#933738',bg:'#fff8f0',layout:'editorial',items:['The long read','In conversation','From the notebook']},
 {id:'realestate',name:'Property showcase',group:'Business',brand:'Haven Homes',headline:'Find a place to call your own.',intro:'Explore spaces with character and get in touch for a personal viewing.',color:'#455d72',bg:'#f3f5f5',layout:'catalog',items:['City living','Room to grow','A quieter setting']}
] as const;
export function templateFiles(id:string):Record<string,string>|null{const t=extraTemplates.find(t=>t.id===id);if(!t)return null;const dark=t.id==='photography';const section=(name:string,body:string)=>`<section data-wb-block="${name}">${body}</section>`;
 const cards=t.items.map((item,i)=>`<article data-wb-block="${item}">${['gallery','catalog'].includes(t.layout)?`<div class="image-placeholder" role="img" aria-label="Replace with your own image">${String(i+1).padStart(2,'0')}</div>`:''}<p class="eyebrow">${String(i+1).padStart(2,'0')}</p><h2>${item}</h2><p>Replace this sample with your own details, story, or description.</p>${t.layout==='menu'?'<p class="price">Add your prices here</p>':''}</article>`).join('\n');
 let body=section('Introduction',`<div class="hero ${t.layout}"><p class="eyebrow">${t.brand}</p><h1>${t.headline}</h1><p class="intro">${t.intro}</p><a class="button" href="#contact">${t.id==='event'?'Ask about attending':t.id==='restaurant'?'Plan your visit':t.id==='resume'?'Get in touch':'Discover more'}</a></div>`);
 body+=section('Highlights',`<div class="collection ${t.layout}">${cards}</div>`);
 if(t.layout==='menu')body+=section('At the table','<h2>A menu with the seasons.</h2><dl class="menu-list"><dt>From the garden</dt><dd>Add a dish and its description.</dd><dt>From the kitchen</dt><dd>Add a signature dish and price.</dd><dt>Something sweet</dt><dd>Add your favorite finishing touch.</dd></dl>');
 if(t.layout==='resume')body+=section('Experience','<h2>Experience</h2><ol class="timeline"><li><h3>Current role</h3><p>Organization · Dates · Your contribution</p></li><li><h3>Previous role</h3><p>Organization · Dates · Your contribution</p></li></ol>');
 body+=`<section id="contact" data-wb-block="Contact" class="contact"><p class="eyebrow">Let’s talk</p><h2>${t.id==='restaurant'?'Visit us soon.':'Start a conversation.'}</h2><p>Add your address, opening hours, and preferred contact details here.</p><a href="mailto:hello@example.com">hello@example.com</a></section>`;
 const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${t.intro}"><title>${t.brand}</title><link rel="stylesheet" href="styles.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="index.html">${t.brand}</a><nav aria-label="Main navigation"><a href="#main">Explore</a><a href="#contact">Contact</a></nav></header><main id="main">${body}</main><footer><p>© ${t.brand} · Replace sample content before publishing.</p></footer></body></html>`;
 const css=`:root{font-family:${['menu','editorial'].includes(t.layout)?'Georgia,serif':'system-ui,sans-serif'};color:${dark?'#f8f3ea':'#22292e'};background:${t.bg};--accent:${t.color}}*{box-sizing:border-box}body{margin:0}a{color:inherit}header,main,footer{max-width:1160px;margin:auto;padding:28px 36px}header{display:flex;justify-content:space-between;gap:24px;align-items:center;border-bottom:1px solid #8884}nav{display:flex;gap:24px}.brand{font-weight:800;font-size:1.2rem;text-decoration:none}.hero{padding:70px 0;max-width:850px}.hero.center{margin:auto;text-align:center}.hero.split{border-left:8px solid var(--accent);padding-left:32px}.hero.menu{text-align:center;margin:auto;border-block:1px solid var(--accent)}h1{font-size:clamp(2.5rem,7vw,5.8rem);line-height:1.04;letter-spacing:-.045em;margin:20px 0}h2{font-size:1.7rem;line-height:1.2}.intro{font-size:1.2rem;line-height:1.8;max-width:680px}.eyebrow{text-transform:uppercase;letter-spacing:.15em;font-size:.75rem;color:var(--accent);font-weight:700}.button{display:inline-block;background:var(--accent);color:white;padding:15px 24px;border-radius:6px;text-decoration:none;margin-top:18px}.collection{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:24px;padding:28px 0 60px}.collection article{padding:22px;border:1px solid #8884;border-radius:10px}.collection.schedule,.collection.resume{grid-template-columns:1fr;max-width:850px}.collection.schedule article{display:grid;grid-template-columns:70px 1fr;gap:0 20px;border-radius:0;border-inline:0}.collection.schedule article p:last-child{grid-column:2}.collection.editorial article:first-child{grid-column:span 2}.collection.gallery article{padding:0;border:0}.collection.gallery article:nth-child(2){padding-top:65px}.image-placeholder{min-height:240px;background:linear-gradient(140deg,var(--accent),${dark?'#35383e':'#ded7ce'});display:grid;place-items:center;color:white;font-size:3rem;border-radius:7px}.collection.catalog .image-placeholder{aspect-ratio:1}.contact{padding:55px 30px;border-top:2px solid var(--accent);background:#8881;border-radius:8px}.menu-list{display:grid;grid-template-columns:1fr 2fr;gap:24px;padding:30px;border-top:1px solid #8884}.menu-list dt{font-weight:bold}.timeline{border-left:2px solid var(--accent);padding-left:35px}.timeline li{padding:15px}.skip{position:absolute;left:-9999px}.skip:focus{left:15px;top:15px;background:${t.bg};padding:12px}p{line-height:1.7}footer{font-size:.8rem;opacity:.8}@media(max-width:700px){header,main,footer{padding:22px}.collection{grid-template-columns:1fr}.collection.editorial article:first-child{grid-column:auto}.collection.gallery article:nth-child(2){padding-top:0}.hero{padding:40px 0}.menu-list{grid-template-columns:1fr}.menu-list dd{margin:0}header{flex-wrap:wrap}}`;
 return {'index.html':html,'styles.css':css,'webbit.json':JSON.stringify({format:1,name:t.brand,entry:'index.html',template:t.id},null,2),'TEMPLATE-README.txt':'Original Webbit starter. Replace all sample content and images. Catalogs, event inquiries and contact links do not provide checkout, ticketing or form processing. No remote assets or required services. Layout research: Bootstrap examples and HTML5 UP; no third-party template source or artwork copied.'};
}
